Ext6.define('common.Drug.models.DrugFormModel', {
	extend: 'Ext6.data.Model',
	alias: 'model.DrugFormModel',
	idProperty: 'EvnDrug_id',
	fields: [
		{ name: 'EvnDrug_id' },
		{ name: 'EvnDrug_setDate', type: 'date', dateFormat: 'd.m.Y' },
		{ name: 'EvnDrug_setTime' },
		{ name: 'Person_id' },
		{ name: 'EvnCourse_id' },
		{ name: 'EvnPrescr_id' },
		{ name: 'EvnCourseTreatDrug_id' },
		{ name: 'EvnPrescrTreatDrug_id' },
		{ name: 'EvnPrescrTreat_Fact' },
		{ name: 'PrescrFactCountDiff' },
		{ name: 'EvnDrug_pid' },
		{ name: 'EvnDrug_rid'},
		{ name: 'Server_id' },
		{ name: 'PersonEvn_id' },
		{ name: 'Drug_id' },
		{ name: 'DrugPrepFas_id' },
		{ name: 'LpuSection_id' },
		{ name: 'EvnDrug_Price' },
		{ name: 'EvnDrug_Sum' },
		{ name: 'DocumentUc_id' },
		{ name: 'DocumentUcStr_id' },
		{ name: 'DocumentUcStr_oid' },
		{ name: 'Storage_id' },
		{ name: 'Mol_id' },
		{ name: 'EvnDrug_Kolvo' },
		{ name: 'EvnDrug_KolvoEd' },
		{ name: 'EvnDrug_RealKolvo' },
		{ name: 'GoodsUnit_id' }
	]
});