<?php

class LpuStructure_model_inputRules
{
	/**
	 * Правила для входящих параметров
	 *
	 * @return array
	 */
	public static function getInputRules()
	{
		return [
			"createLpuUnit" => [
				["field" => "LpuBuilding_id", "label" => "Идентификатор подразделения", "rules" => "required", "type" => "id"],
				["field" => "LpuUnitType_id", "label" => "Тип группы отделений", "rules" => "required", "type" => "id"],
				["field" => "LpuUnitTypeDop_id", "label" => "Дополнительный тип группы отделений", "rules" => "", "type" => "id"],
				["field" => "Address_id", "label" => "Адрес группы отделений", "rules" => "", "type" => "id"],
				["field" => "LpuUnit_Code", "label" => "Код группы отделений", "rules" => "required|is_numeric|is_natural_no_zero|max_length[5]", "type" => "string"],
				["field" => "LpuUnit_Name", "label" => "Наименование группы отделений", "rules" => "required", "type" => "string"],
				["field" => "LpuUnit_Descr", "label" => "Комментарии по записи на прием", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_Phone", "label" => "Телефон записи на прием", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_IsEnabled", "label" => "Признак активности", "rules" => "", "type" => "api_flag"],
				["field" => "LpuUnit_isPallCC", "label" => "Признак центра паллиативной медицинской помощи (ПМП]", "rules" => "", "type" => "api_flag"],
				["field" => "LpuUnit_IsDirWithRec", "label" => "Признак записи", "rules" => "", "type" => "api_flag"],
				["field" => "LpuUnit_ExtMedCnt", "label" => "Признак приема по скорой помощи", "rules" => "", "type" => "int"],
				["field" => "LpuUnit_Email", "label" => "Электронная почта", "rules" => "trim", "type" => "string"],
				["field" => "LpuUnit_IP", "label" => "Адрес и способ подключения", "rules" => "trim", "type" => "string"],
				["field" => "LpuUnitSet_id", "label" => "Идентификатор объединения групп отделений", "rules" => "", "type" => "id"],
				["field" => "LpuUnit_Guid", "label" => "ГУИД", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_begDate", "label" => "Дата начала действия записи", "rules" => "", "type" => "date"],
				["field" => "LpuUnit_endDate", "label" => "Дата окончания действия записи", "rules" => "", "type" => "date"],
				["field" => "LpuUnit_IsOMS", "label" => "Признак Работает по ОМС", "rules" => "", "type" => "api_flag"],
				["field" => "UnitDepartType_fid", "label" => "Тип (ФРМО]", "rules" => "required", "type" => "id"],
				["field" => "LpuUnitProfile_fid", "label" => "Профиль (ФРМО]", "rules" => "", "type" => "id"],
				["field" => "LpuUnit_isStandalone", "label" => "Признак \"Обособленное подразделение\"", "rules" => "required", "type" => "api_flag"],
				["field" => "LpuBuildingPass_id", "label" => "Основное здание", "rules" => "", "type" => "id"],
				["field" => "LpuUnit_isHomeVisit", "label" => "Признак \"Приём на дому\"", "rules" => "", "type" => "api_flag"],
				["field" => "LpuUnit_isCMP", "label" => "Признак \"Приём скорой помощи\"", "rules" => "", "type" => "api_flag"],
				["field" => "LpuUnit_FRMOUnitID", "label" => "Идентификатор ФРМО", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_FRMOid", "label" => "Идентификатор ФРМО для структурного подразделения", "rules" => "", "type" => "id"],
			],
			"updateLpuUnit" => [
				["field" => "LpuUnit_id", "label" => "Идентификатор группы отделений", "rules" => "required", "type" => "id"],
				["field" => "LpuUnitType_id", "label" => "Тип группы отделений", "rules" => "required", "type" => "id"],
				["field" => "LpuUnitTypeDop_id", "label" => "Дополнительный тип группы отделений", "rules" => "", "type" => "id"],
				["field" => "Address_id", "label" => "Адрес группы отделений", "rules" => "", "type" => "id"],
				['field' => 'LpuUnit_Code', 'label' => 'Код группы отделений', 'rules' => 'required|is_numeric|is_natural_no_zero|max_length[5]', 'type' => 'string'],
				["field" => "LpuUnit_Name", "label" => "Наименование группы отделений", "rules" => "required", "type" => "string"],
				["field" => "LpuUnit_Descr", "label" => "Комментарии по записи на прием", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_Phone", "label" => "Телефон записи на прием", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_IsEnabled", "label" => "Признак активности", "rules" => "", "type" => "api_flag"],
				["field" => "LpuUnit_isPallCC", "label" => "Признак центра паллиативной медицинской помощи (ПМП]", "rules" => "", "type" => "api_flag"],
				["field" => "LpuUnit_IsDirWithRec", "label" => "Признак записи", "rules" => "", "type" => "api_flag"],
				["field" => "LpuUnit_ExtMedCnt", "label" => "Признак приема по скорой помощи", "rules" => "", "type" => "int"],
				["field" => "LpuUnit_Email", "label" => "Электронная почта", "rules" => "trim", "type" => "string"],
				["field" => "LpuUnit_IP", "label" => "Адрес и способ подключения", "rules" => "trim", "type" => "string"],
				["field" => "LpuUnitSet_id", "label" => "Идентификатор объединения групп отделений", "rules" => "", "type" => "id"],
				["field" => "LpuUnit_Guid", "label" => "ГУИД", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_begDate", "label" => "Дата начала действия записи", "rules" => "", "type" => "date"],
				["field" => "LpuUnit_endDate", "label" => "Дата окончания действия записи", "rules" => "", "type" => "date"],
				["field" => "LpuUnit_IsOMS", "label" => "Признак Работает по ОМС", "rules" => "", "type" => "api_flag"],
				["field" => "UnitDepartType_fid", "label" => "Тип (ФРМО]", "rules" => "required", "type" => "id"],
				["field" => "LpuUnitProfile_fid", "label" => "Профиль (ФРМО]", "rules" => "", "type" => "id"],
				["field" => "LpuUnit_isStandalone", "label" => "Признак \"Обособленное подразделение\"", "rules" => "required", "type" => "api_flag"],
				["field" => "LpuBuildingPass_id", "label" => "Основное здание", "rules" => "", "type" => "id"],
				["field" => "LpuUnit_isHomeVisit", "label" => "Признак \"Приём на дому\"", "rules" => "", "type" => "api_flag"],
				["field" => "LpuUnit_isCMP", "label" => "Признак \"Приём скорой помощи\"", "rules" => "", "type" => "api_flag"],
				["field" => "LpuUnit_FRMOUnitID", "label" => "Идентификатор ФРМО", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_FRMOid", "label" => "Идентификатор ФРМО для структурного подразделения", "rules" => "", "type" => "id"],
			],
			"getLpuUnitById" => [
				['field' => 'LpuUnit_id', 'label' => 'Идентификатор группы отделений', 'rules' => '', 'type' => 'id'],
				['field' => 'LpuUnit_OID', 'label' => 'OID структурного подразделения в справочнике структурных подразделений ФРМО', 'rules' => '', 'type' => 'string']
			],
			"getLpuUnitList" => [
				["field" => "LpuBuilding_id", "label" => "Идентификатор подразделения", "rules" => "required", "type" => "id"],
			],
			"createLpuSection" => [
				["field" => "LpuUnit_id", "label" => "Идентификатор группы отделений", "rules" => "required", "type" => "id"],
				["field" => "LpuSection_setDate", "label" => "Дата создания отделения", "rules" => "required", "type" => "date"],
				["field" => "LpuSection_disDate", "label" => "Дата закрытия отделения", "rules" => "", "type" => "date"],
				["field" => "LpuSectionProfile_Code", "label" => "Код профиля отделения", "rules" => "required", "type" => "string"],
				["field" => "LpuSection_Code", "label" => "Код отделения", "rules" => "", "type" => "string"],
				["field" => "LpuSectionCode_id", "label" => "Код отделения", "rules" => "", "type" => "id"],
				["field" => "LpuSection_Name", "label" => "Наименование отделения", "rules" => "required", "type" => "string"],
				["field" => "MesAgeGroup_id", "label" => "Идентификатор фозрастной группы", "rules" => "", "type" => "id"],
				["field" => "MESLevel_id", "label" => "Идентификатор уровня МЭС", "rules" => "", "type" => "id"],
				["field" => "LpuSection_IsHTMedicalCare", "label" => "Флаг выполненеия ВМП", "rules" => "required", "type" => "api_flag"],
				["field" => "LpuSection_KolAmbul", "label" => "Количество бригад скорой помощи", "rules" => "", "type" => "int"],
				["field" => "LpuSection_KolJob", "label" => "Количество рабочих мест", "rules" => "", "type" => "int"],
				["field" => "LpuSection_PlanAutopShift", "label" => "Плановое число вскрытий за смену", "rules" => "", "type" => "int"],
				["field" => "LpuSection_PlanResShift", "label" => "Плановое число исследований в смену", "rules" => "", "type" => "int"],
				["field" => "LpuSection_PlanTrip", "label" => "Плановое число выездов в смену", "rules" => "", "type" => "int"],
				["field" => "LpuSection_PlanVisitDay", "label" => "Плановое число посещений в сутки", "rules" => "", "type" => "int"],
				["field" => "LpuSection_PlanVisitShift", "label" => "Плановое число посещений в смену", "rules" => "", "type" => "int"],
				["field" => "LpuSectionAge_id", "label" => "Идентификатор типа отделения по возрасту", "rules" => "", "type" => "id"],
				["field" => "LpuSectionBedProfile_id", "label" => "Идентификатор профиля коек", "rules" => "", "type" => "id"],
				["field" => "LpuSectionOuter_id", "label" => "Идентификатор отделения МО в сторонней МИС", "rules" => "", "type" => "id"],
				["field" => "FRMPSubdivision_id", "label" => "Код типа отделения (по ФРМР] для формы 30", "rules" => "required", "type" => "id"],
				["field" => "LpuBuildingPass_id", "label" => "Идентификатор здания МО", "rules" => "", "type" => "id"],
			],
			"createLpuSectionDopProfile" => [
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionProfile_id", "label" => "Идентификатор профиля отделения", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionLpuSectionProfile_begDate", "label" => "Дата начала действия дополнительного профиля отделения", "rules" => "required", "type" => "date"],
				["field" => "LpuSectionLpuSectionProfile_endDate", "label" => "Дата окончания действия дополнительного профиля отделения", "rules" => "", "type" => "date"],
			],
			"deleteLpuSection" => [
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "required", "type" => "id"],
			],
			"deleteLpuSectionDopProfile" => [
				["field" => "LpuSectionLpuSectionProfile_id", "label" => "Идентификатор дополнительного профиля отделения", "rules" => "required", "type" => "id"],
			],
			"createLpuSectionBedState" => [
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionBedProfile_id", "label" => "Идентификатор профиля коек", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionProfile_id", "label" => "Идентификатор профиля", "rules" => "", "type" => "id"],
				["field" => "LpuSectionBedProfileLink_fedid", "label" => "Идентификатор стыковочной таблицы", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionBedState_ProfileName", "label" => "Наименование", "rules" => "", "type" => "string"],
				["field" => "LpuSectionBedState_Fact", "label" => "Фактическое количество", "rules" => "required", "type" => "int"],
				["field" => "LpuSectionBedState_Plan", "label" => "Планируемое количество", "rules" => "required", "type" => "int"],
				["field" => "LpuSectionBedState_Repair", "label" => "Отклонение от планируемого количества", "rules" => "required", "type" => "int"],
				["field" => "LpuSectionBedState_CountOms", "label" => "Количество коек, оплачиваемых по ОМС", "rules" => "", "type" => "int"],
				["field" => "LpuSectionBedState_MalePlan", "label" => "Мужские койки. Плановое количество", "rules" => "", "type" => "int"],
				["field" => "LpuSectionBedState_MaleFact", "label" => "Мужские койки Фактическое количество", "rules" => "", "type" => "int"],
				["field" => "LpuSectionBedState_FemalePlan", "label" => "Женские койки. Плановое количество", "rules" => "", "type" => "int"],
				["field" => "LpuSectionBedState_FemaleFact", "label" => "Женские койки. Фактическое количество", "rules" => "", "type" => "int"],
				["field" => "LpuSectionBedState_begDate", "label" => "Дата начала", "rules" => "required", "type" => "date"],
				["field" => "LpuSectionBedState_endDate", "label" => "Дата окончания", "rules" => "", "type" => "date"],
			],
			"updateLpuSectionBedState" => [
				["field" => "LpuSectionBedState_id", "label" => "Идентификатор коек и их профилей в отделении МО", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionBedProfile_id", "label" => "Идентификатор профиля коек", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionProfile_id", "label" => "Идентификатор профиля", "rules" => "", "type" => "id"],
				["field" => "LpuSectionBedProfileLink_fedid", "label" => "Идентификатор стыковочной таблицы", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionBedState_ProfileName", "label" => "Наименование", "rules" => "", "type" => "string"],
				["field" => "LpuSectionBedState_Fact", "label" => "Фактическое количество", "rules" => "required", "type" => "int"],
				["field" => "LpuSectionBedState_Plan", "label" => "Планируемое количество", "rules" => "required", "type" => "int"],
				["field" => "LpuSectionBedState_Repair", "label" => "Отклонение от планируемого количества", "rules" => "required", "type" => "int"],
				["field" => "LpuSectionBedState_CountOms", "label" => "Количество коек, оплачиваемых по ОМС", "rules" => "", "type" => "int"],
				["field" => "LpuSectionBedState_MalePlan", "label" => "Мужские койки. Плановое количество", "rules" => "", "type" => "int"],
				["field" => "LpuSectionBedState_MaleFact", "label" => "Мужские койки Фактическое количество", "rules" => "", "type" => "int"],
				["field" => "LpuSectionBedState_FemalePlan", "label" => "Женские койки. Плановое количество", "rules" => "", "type" => "int"],
				["field" => "LpuSectionBedState_FemaleFact", "label" => "Женские койки. Фактическое количество", "rules" => "", "type" => "int"],
				["field" => "LpuSectionBedState_begDate", "label" => "Дата начала", "rules" => "required", "type" => "date"],
				["field" => "LpuSectionBedState_endDate", "label" => "Дата окончания", "rules" => "", "type" => "date"],
			],
			"deleteLpuSectionBedState" => [
				["field" => "LpuSectionBedState_id", "label" => "Идентификатор коек и их профилей в отделении МО", "rules" => "required", "type" => "id"],
			],
			"getLpuSectionBedStateListBySection" => [
				["field" => "LpuSection_id", "label" => "Идентификатор отделения МО", "rules" => "required", "type" => "id"],
			],
			"getLpuBuildingById" => [
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "required", "type" => "id", "equalsession" => true],
				["field" => "LpuBuilding_id", "label" => "Идентификатор подразделения", "rules" => "required", "type" => "id"],
			],
			"getLpuRegionByID" => [
				["field" => "LpuRegion_id", "label" => "Идентификатор участка", "rules" => "required", "type" => "id"]
			],
			"getLpuRegionByМО" => [
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "required", "type" => "id"]
			],
			"getLpuRegionWorkerPlaceByID" => [
				["field" => "MedStaffRegion_id", "label" => "Идентификатор периода работы врача на участке", "rules" => "required", "type" => "id"]
			],
			"getLpuRegionWorkerPlaceByRegion" => [
				["field" => "LpuRegion_id", "label" => "Идентификатор участка", "rules" => "required", "type" => "id"]
			],
			"getLpuRegionWorkerPlaceListByMedStaffFact" => [
				["field" => "MedStaffFact_id", "label" => "Идентификатор места работы", "rules" => "required", "type" => "id"]
			],
			"getLpuRegionWorkerPlaceListByTime" => [
				["field" => "LpuRegion_id", "label" => "Идентификатор участка", "rules" => "required", "type" => "id"],
				["field" => "MedStaffFact_id", "label" => "Идентификатор места работы", "rules" => "required", "type" => "id"],
				["field" => "MedStaffRegion_begDate", "label" => "Дата начала периода", "rules" => "required", "type" => "date"],
				["field" => "MedStaffRegion_endDate", "label" => "Дата окончания периода", "rules" => "", "type" => "date"],
			],
			"getLpuBuildingListByCodeAndName" => [
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "required", "type" => "id"],
				["field" => "LpuBuilding_Code", "label" => "Код подразделения", "rules" => "required", "type" => "string"],
				["field" => "LpuBuilding_Name", "label" => "Наименование подразделения", "rules" => "", "type" => "string"],
			],
			"getLpuBuildingListByMO" => [
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "required", "type" => "id"],
				["field" => "extended", "label" => "Признак возврата дополнительных полей", "rules" => "", "type" => "int"],
			],
			"getLpuListByRegion" => [
				["field" => "Region_id", "label" => "Код региона", "rules" => "required", "type" => "int"],
				["field" => "offset", "label" => "Смещение", "rules" => "", "type" => "int"],
				["field" => "allowTest", "label" => "Признак возврата тестовых МО", "rules" => "", "type" => "int"],
				["field" => "extended", "label" => "Признак возврата дополнительных полей", "rules" => "", "type" => "int"],
			],
			"getLpuListBySubRgn" => [
				["field" => "SubRgn_id", "label" => "Идентификатор района", "rules" => "required", "type" => "id"],
				["field" => "Extended", "label" => "Признак возврата дополнительных полей", "rules" => "", "type" => "int"],
			],
			"getLpuSectionById" => [
				["field" => "LpuSection_id", "label" => "Идентификатор отделения МО", "rules" => "", "type" => "id"],
				["field" => "LpuSectionOuter_id", "label" => "Идентификатор отделения МО в сторонней МИС", "rules" => "", "type" => "id"],
			],
			"getLpuSectionDopProfileList" => [
				['field' => 'LpuSection_id', 'label' => 'Идентификатор отделения', 'rules' => '', 'type' => 'id'],
			],
			"getLpuSectionListByBuilding" => [
				["field" => "LpuBuilding_id", "label" => "Идентификатор подразделения", "rules" => "required", "type" => "id"],
			],
			"getLpuSectionListByCodeAndName" => [
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "required", "type" => "id"],
				["field" => "LpuSection_Code", "label" => "Код отделения", "rules" => "", "type" => "string"],
				["field" => "LpuSectionCode_Code", "label" => "Код отделения", "rules" => "", "type" => "string"],
				["field" => "LpuSection_Name", "label" => "Наименование отделения", "rules" => "required", "type" => "string"],
			],
			"getLpuSectionListByMO" => [
				['field' => 'Lpu_id', 'label' => 'Идентификатор МО', 'rules' => '', 'type' => 'id'],
			],
			"saveLpuBuilding" => [
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "required", "type" => "id"],
				["field" => "LpuBuilding_id", "label" => "Идентификатор подразделения", "rules" => "", "type" => "id"],
				["field" => "LpuBuilding_begDate", "label" => "Период действия с", "rules" => "", "type" => "date"],
				["field" => "LpuBuilding_endDate", "label" => "Период действия по", "rules" => "", "type" => "date"],
				["field" => "LpuBuilding_Code", "label" => "Код подразделения", "rules" => "required|is_numeric|is_natural_no_zero", "type" => "int"],
				["field" => "LpuBuilding_IsExport", "label" => "Признак \"Выгружать в ПМУ\"", "rules" => "", "type" => "id"],
				["field" => "LpuBuilding_Name", "label" => "Наименование подразделения", "rules" => "required", "type" => "string"],
				["field" => "LpuBuilding_Nick", "label" => "Краткое наименование подразделения", "rules" => "", "type" => "string"],
				["field" => "LpuBuilding_WorkTime", "label" => "Время работы", "rules" => "", "type" => "string"],
				["field" => "LpuBuilding_RoutePlan", "label" => "Схема проезда", "rules" => "", "type" => "string"],
				["field" => "LpuBuildingType_id", "label" => "Идентификатор типа подразделения", "rules" => "required", "type" => "id"],
				["field" => "LpuBuilding_CmpStationCode", "label" => "Код станции", "rules" => "", "type" => "string"],
				["field" => "LpuBuilding_CmpSubstationCode", "label" => "Код подстанции", "rules" => "", "type" => "string"],
				["field" => "PAddress_id", "label" => "Идентификатор адреса для выписки рецептов", "rules" => "", "type" => "id"],
				["field" => "Address_id", "label" => "Идентификатор адреса", "rules" => "", "type" => "id"],
				["field" => "Address_Address", "label" => "Адрес", "rules" => "", "type" => "string"],
				["field" => "Address_House", "label" => "Дом", "rules" => "", "type" => "string"],
				["field" => "Address_Corpus", "label" => "Корпус", "rules" => "", "type" => "string"],
				["field" => "Address_Flat", "label" => "Квартира", "rules" => "", "type" => "string"],
				["field" => "Address_Zip", "label" => "Индекс", "rules" => "", "type" => "string"],
				["field" => "KLCountry_id", "label" => "Идентификатор страны", "rules" => "", "type" => "id"],
				["field" => "KLRGN_id", "label" => "Идентификатор региона", "rules" => "", "type" => "id"],
				["field" => "KLSubRGN_id", "label" => "Идентификатор района", "rules" => "", "type" => "id"],
				["field" => "KLCity_id", "label" => "Идентификатор города", "rules" => "", "type" => "id"],
				["field" => "KLTown_id", "label" => "Идентификатор населенного пункта", "rules" => "", "type" => "id"],
				["field" => "KLStreet_id", "label" => "Идентификатор улицы", "rules" => "", "type" => "id"],
				["field" => "PAddress_Address", "label" => "Адрес", "rules" => "", "type" => "string"],
				["field" => "PAddress_House", "label" => "Дом", "rules" => "", "type" => "string"],
				["field" => "PAddress_Corpus", "label" => "Корпус", "rules" => "", "type" => "string"],
				["field" => "PAddress_Flat", "label" => "Квартира", "rules" => "", "type" => "string"],
				["field" => "PAddress_Zip", "label" => "Индекс", "rules" => "", "type" => "string"],
				["field" => "PKLCountry_id", "label" => "Идентификатор страны", "rules" => "", "type" => "id"],
				["field" => "PKLRGN_id", "label" => "Идентификатор региона", "rules" => "", "type" => "id"],
				["field" => "PKLSubRGN_id", "label" => "Идентификатор района", "rules" => "", "type" => "id"],
				["field" => "PKLCity_id", "label" => "Идентификатор города", "rules" => "", "type" => "id"],
				["field" => "PKLTown_id", "label" => "Идентификатор населенного пункта", "rules" => "", "type" => "id"],
				["field" => "PKLStreet_id", "label" => "Идентификатор улицы", "rules" => "", "type" => "id"],
				["field" => "LpuBuilding_Latitude", "label" => "Координаты широты", "rules" => "", "type" => "float"],
				["field" => "LpuBuilding_Longitude", "label" => "Координаты долготы", "rules" => "", "type" => "float"],
				["field" => "LpuFilial_id", "label" => "Идентификатор филиала", "rules" => "", "type" => "id"],
				["field" => "LpuBuilding_IsAIDSCenter", "label" => "СПИД-центр", "rules" => "", "type" => "swcheckbox"],
				["field" => "LpuBuildingHealth_Phone", "label" => "Телефон кабинета здоровья", "rules" => "", "type" => "string"],
				["field" => "LpuBuildingHealth_Email", "label" => "Электронная почта кабинета здоровья", "rules" => "", "type" => "string"],
			],
			"createLpuBuilding" => [
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "required", "type" => "id", "equalsession" => true],
				["field" => "LpuBuilding_begDate", "label" => "Период действия с", "rules" => "", "type" => "date"],
				["field" => "LpuBuilding_endDate", "label" => "Период действия по", "rules" => "", "type" => "date"],
				["field" => "LpuBuilding_Code", "label" => "Код подразделения", "rules" => "required|is_numeric|is_natural_no_zero", "type" => "int"],
				["field" => "LpuBuilding_IsExport", "label" => "Признак \"Выгружать в ПМУ\"", "rules" => "required", "type" => "api_flag"],
				["field" => "LpuBuilding_Name", "label" => "Наименование подразделения", "rules" => "required", "type" => "string"],
				["field" => "LpuBuilding_Nick", "label" => "Краткое наименование подразделения", "rules" => "", "type" => "string"],
				["field" => "LpuBuilding_WorkTime", "label" => "Время работы", "rules" => "", "type" => "string"],
				["field" => "LpuBuilding_RoutePlan", "label" => "Схема проезда", "rules" => "", "type" => "string"],
				["field" => "LpuBuildingType_id", "label" => "Идентификатор типа подразделения", "rules" => "required", "type" => "id"],
				["field" => "LpuBuilding_CmpStationCode", "label" => "Код станции", "rules" => "", "type" => "string"],
				["field" => "LpuBuilding_CmpSubstationCode", "label" => "Код подстанции", "rules" => "", "type" => "string"],
				["field" => "PAddress_id", "label" => "Идентификатор адреса для выписки рецептов", "rules" => "", "type" => "id"],
				["field" => "Address_id", "label" => "Идентификатор адреса", "rules" => "", "type" => "id"],
				["field" => "Address_Address", "label" => "Адрес", "rules" => "", "type" => "string"],
				["field" => "Address_House", "label" => "Дом", "rules" => "", "type" => "string"],
				["field" => "Address_Corpus", "label" => "Корпус", "rules" => "", "type" => "string"],
				["field" => "Address_Flat", "label" => "Квартира", "rules" => "", "type" => "string"],
				["field" => "Address_Zip", "label" => "Индекс", "rules" => "", "type" => "string"],
				["field" => "KLCountry_id", "label" => "Идентификатор страны", "rules" => "", "type" => "id"],
				["field" => "KLRGN_id", "label" => "Идентификатор региона", "rules" => "", "type" => "id"],
				["field" => "KLSubRGN_id", "label" => "Идентификатор района", "rules" => "", "type" => "id"],
				["field" => "KLCity_id", "label" => "Идентификатор города", "rules" => "", "type" => "id"],
				["field" => "KLTown_id", "label" => "Идентификатор населенного пункта", "rules" => "", "type" => "id"],
				["field" => "KLStreet_id", "label" => "Идентификатор улицы", "rules" => "", "type" => "id"],
				["field" => "PAddress_Address", "label" => "Адрес", "rules" => "", "type" => "string"],
				["field" => "PAddress_House", "label" => "Дом", "rules" => "", "type" => "string"],
				["field" => "PAddress_Corpus", "label" => "Корпус", "rules" => "", "type" => "string"],
				["field" => "PAddress_Flat", "label" => "Квартира", "rules" => "", "type" => "string"],
				["field" => "PAddress_Zip", "label" => "Индекс", "rules" => "", "type" => "string"],
				["field" => "PKLCountry_id", "label" => "Идентификатор страны", "rules" => "", "type" => "id"],
				["field" => "PKLRGN_id", "label" => "Идентификатор региона", "rules" => "", "type" => "id"],
				["field" => "PKLSubRGN_id", "label" => "Идентификатор района", "rules" => "", "type" => "id"],
				["field" => "PKLCity_id", "label" => "Идентификатор города", "rules" => "", "type" => "id"],
				["field" => "PKLTown_id", "label" => "Идентификатор населенного пункта", "rules" => "", "type" => "id"],
				["field" => "PKLStreet_id", "label" => "Идентификатор улицы", "rules" => "", "type" => "id"],
				["field" => "LpuBuilding_Latitude", "label" => "Координаты широты", "rules" => "", "type" => "float"],
				["field" => "LpuBuilding_Longitude", "label" => "Координаты долготы", "rules" => "", "type" => "float"],
			],
			"updateLpuBuilding" => [
				["field" => "LpuBuilding_id", "label" => "Идентификатор подразделения", "rules" => "required", "type" => "id"],
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "", "type" => "id", "equalsession" => true],
				["field" => "LpuBuilding_begDate", "label" => "Период действия с", "rules" => "", "type" => "date"],
				["field" => "LpuBuilding_endDate", "label" => "Период действия по", "rules" => "", "type" => "date"],
				["field" => "LpuBuilding_Code", "label" => "Код подразделения", "rules" => "is_numeric|is_natural_no_zero", "type" => "int"],
				["field" => "LpuBuilding_IsExport", "label" => "Признак \"Выгружать в ПМУ\"", "rules" => "", "type" => "api_flag"],
				["field" => "LpuBuilding_Name", "label" => "Наименование подразделения", "rules" => "", "type" => "string"],
				["field" => "LpuBuilding_Nick", "label" => "Краткое наименование подразделения", "rules" => "", "type" => "string"],
				["field" => "LpuBuilding_WorkTime", "label" => "Время работы", "rules" => "", "type" => "string"],
				["field" => "LpuBuilding_RoutePlan", "label" => "Схема проезда", "rules" => "", "type" => "string"],
				["field" => "LpuBuildingType_id", "label" => "Идентификатор типа подразделения", "rules" => "", "type" => "id"],
				["field" => "LpuBuilding_CmpStationCode", "label" => "Код станции", "rules" => "", "type" => "string"],
				["field" => "LpuBuilding_CmpSubstationCode", "label" => "Код подстанции", "rules" => "", "type" => "string"],
				["field" => "PAddress_id", "label" => "Идентификатор адреса для выписки рецептов", "rules" => "", "type" => "id"],
				["field" => "Address_id", "label" => "Идентификатор адреса", "rules" => "", "type" => "id"],
				["field" => "Address_Address", "label" => "Адрес", "rules" => "", "type" => "string"],
				["field" => "Address_House", "label" => "Дом", "rules" => "", "type" => "string"],
				["field" => "Address_Corpus", "label" => "Корпус", "rules" => "", "type" => "string"],
				["field" => "Address_Flat", "label" => "Квартира", "rules" => "", "type" => "string"],
				["field" => "Address_Zip", "label" => "Индекс", "rules" => "", "type" => "string"],
				["field" => "KLCountry_id", "label" => "Идентификатор страны", "rules" => "", "type" => "id"],
				["field" => "KLRGN_id", "label" => "Идентификатор региона", "rules" => "", "type" => "id"],
				["field" => "KLSubRGN_id", "label" => "Идентификатор района", "rules" => "", "type" => "id"],
				["field" => "KLCity_id", "label" => "Идентификатор города", "rules" => "", "type" => "id"],
				["field" => "KLTown_id", "label" => "Идентификатор населенного пункта", "rules" => "", "type" => "id"],
				["field" => "KLStreet_id", "label" => "Идентификатор улицы", "rules" => "", "type" => "id"],
				["field" => "PAddress_Address", "label" => "Адрес", "rules" => "", "type" => "string"],
				["field" => "PAddress_House", "label" => "Дом", "rules" => "", "type" => "string"],
				["field" => "PAddress_Corpus", "label" => "Корпус", "rules" => "", "type" => "string"],
				["field" => "PAddress_Flat", "label" => "Квартира", "rules" => "", "type" => "string"],
				["field" => "PAddress_Zip", "label" => "Индекс", "rules" => "", "type" => "string"],
				["field" => "PKLCountry_id", "label" => "Идентификатор страны", "rules" => "", "type" => "id"],
				["field" => "PKLRGN_id", "label" => "Идентификатор региона", "rules" => "", "type" => "id"],
				["field" => "PKLSubRGN_id", "label" => "Идентификатор района", "rules" => "", "type" => "id"],
				["field" => "PKLCity_id", "label" => "Идентификатор города", "rules" => "", "type" => "id"],
				["field" => "PKLTown_id", "label" => "Идентификатор населенного пункта", "rules" => "", "type" => "id"],
				["field" => "PKLStreet_id", "label" => "Идентификатор улицы", "rules" => "", "type" => "id"],
				["field" => "LpuBuilding_Latitude", "label" => "Координаты широты", "rules" => "", "type" => "float"],
				["field" => "LpuBuilding_Longitude", "label" => "Координаты долготы", "rules" => "", "type" => "float"],
			],
			"saveLpuRegion" => [
				["field" => "LpuRegion_id", "label" => "Идентификатор участка", "rules" => "", "type" => "id"],
				["field" => "LpuRegion_Name", "label" => "Номер участка", "rules" => "required|is_numeric|is_natural_no_zero", "type" => "int"],
				["field" => "LpuRegion_tfoms", "label" => "Номер участка в ТФОМС", "rules" => "is_numeric|is_natural_no_zero", "type" => "int"],
				["field" => "LpuRegion_Descr", "label" => "Описание участка", "rules" => "", "type" => "string"],
				["field" => "LpuRegionType_id", "label" => "Тип участка", "rules" => "required", "type" => "int"],
				["field" => "LpuRegionType_SysNick", "label" => "Системное наименование типа участка", "rules" => "", "type" => "string"],
				["field" => "LpuRegion_begDate", "label" => "Дата создания", "rules" => "required", "type" => "date"],
				["field" => "LpuRegion_endDate", "label" => "Дата закрытия", "rules" => "", "type" => "date"],
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "required", "type" => "int"],
				["field" => "LpuSection_id", "label" => "Отделение", "rules" => "", "type" => "id"],
				["field" => "LpuRegionMedPersonalData", "label" => "Врачи на участке", "rules" => "", "type" => "string"],
				["field" => "checkPost", "label" => "Признак проверки должности", "rules" => "", "type" => "string"],
				["field" => "checkRegType", "label" => "Признак проверки типа отделения", "rules" => "", "type" => "string"],
				["field" => "checkMainMPDoubles", "label" => "Признак проверки дублей основного врача", "rules" => "", "type" => "string"],
				["field" => "checkLpuSection", "label" => "Признак проверки отделения", "rules" => "", "type" => "string"],
				["field" => "checkStavka", "label" => "Признак проверки ставки", "rules" => "", "type" => "string"],
			],
			"saveLpuSection" => [
				["field" => "LevelType_id", "label" => "Уровень", "rules" => "", "type" => "id"],
				["field" => "LpuCostType_id", "label" => "Признак участия в формировании затрат МО", "rules" => "", "type" => "id"],
				["field" => "LpuSection_CountShift", "label" => "Ставка", "rules" => "", "type" => "int"],
				["field" => "LpuSection_Area", "label" => "Площадь отделения", "rules" => "", "type" => "float"],
				["field" => "LpuSectionType_id", "label" => "Пункт", "rules" => "", "type" => "id"],
				["field" => "MedicalCareKind_id", "label" => "Вид МП", "rules" => "", "type" => "id"],
				["field" => "lpuSectionProfileData", "label" => "Список дополнительных профилей отделения", "rules" => "trim", "type" => "string"],
				['field' => 'lpuSectionMedProductTypeLinkData', 'label' => 'Список медицинского оборудования', 'rules' => 'trim', 'type' => 'string'],
				["field" => "LpuSectionServiceData", "label" => "Список обслуживаемых отделений", "rules" => "trim", "type" => "string"],
				["field" => "AttributeSignValueData", "label" => "Список значний атрибутов", "rules" => "trim", "type" => "string"],
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "", "type" => "id"],
				["field" => "LpuSection_pid", "label" => "Родительский идентификатор отделения", "rules" => "", "type" => "id"],
				["field" => "LpuUnit_id", "label" => "Группа отделений", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionProfile_id", "label" => "Профиль", "rules" => "required", "type" => "id"],
				["field" => "LpuSection_Code", "label" => "Код отделения", "rules" => "trim|required|is_numeric|is_natural|max_length[9]", "type" => "string"],
				["field" => "LpuSectionCode_id", "label" => "Код отделения", "rules" => "", "type" => "id"],
				["field" => "LpuSection_Name", "label" => "Наименование отделения", "rules" => "required", "type" => "string"],
				["field" => "LpuSection_setDate", "label" => "Дата начала действия", "rules" => "", "type" => "date"],
				["field" => "LpuSection_disDate", "label" => "Дата окончания действия", "rules" => "", "type" => "date"],
				["field" => "LpuSectionAge_id", "label" => "Возрастная группа", "rules" => "", "type" => "id"],
				["field" => "LpuSectionBedProfile_id", "label" => "Профиль коек", "rules" => "", "type" => "id"],
				["field" => "MESLevel_id", "label" => "Уровень МЭС", "rules" => "", "type" => "id"],
				["field" => "LpuSection_Descr", "label" => "Примечание", "rules" => "", "type" => "string"],
				["field" => "LpuSection_Contacts", "label" => "Контакты", "rules" => "", "type" => "string"],
				["field" => "LpuSectionHospType_id", "label" => "Вид госпитализации", "rules" => "", "type" => "id"],
				["field" => "LpuSectionDopType_id", "label" => "Доп. тип отделения", "rules" => "", "type" => "id"],
				["field" => "LpuSection_IsDirRec", "label" => "Разрешить запись в отделение через направления", "rules" => "", "type" => "string"],
				["field" => "LpuSection_F14", "label" => "Использовать в форме 14-ОМС", "rules" => "", "type" => "string"],
				["field" => "LpuSection_IsUseReg", "label" => "Использовать данные подотделения в реестрах", "rules" => "", "type" => "string"],
				["field" => "LpuSection_IsQueueOnFree", "label" => "Разрешить помещать в очередь при наличии свободных мест", "rules" => "", "type" => "string"],
				["field" => "LpuSection_PlanAutopShift", "label" => "Плановое число вскрытий в смену", "rules" => "", "type" => "string"],
				["field" => "LpuSection_PlanVisitShift", "label" => "Плановое число посещений в смену", "rules" => "", "type" => "string"],
				["field" => "LpuSection_PlanTrip", "label" => "Плановое число выездов в смену", "rules" => "", "type" => "string"],
				["field" => "LpuSection_KolAmbul", "label" => "Количество бригад скорой помощи", "rules" => "", "type" => "string"],
				["field" => "LpuSection_PlanResShift", "label" => "Плановое число исследований в смену", "rules" => "", "type" => "string"],
				["field" => "LpuSection_KolJob", "label" => "Количество рабочих мест", "rules" => "", "type" => "string"],
				["field" => "LpuSection_PlanVisitDay", "label" => "Плановое число посещений в сутки", "rules" => "", "type" => "string"],
				["field" => "LpuSection_IsCons", "label" => "Консультационное отделение", "rules" => "", "type" => "id"],
				["field" => "LpuSection_IsExportLpuRegion", "label" => "Выгружать участки", "rules" => "", "type" => "id"],
				["field" => "LpuSection_IsHTMedicalCare", "label" => "Выполнение высокотехнологичной медицинской помощи", "rules" => "", "type" => "id"],
				["field" => "LpuSection_IsNoKSG", "label" => "Без КСГ", "rules" => "", "type" => "string"],
				["field" => "LpuSectionMedicalCareKindData", "label" => "Виды оказания МП", "rules" => "trim", "type" => "string"],
				["field" => "FRMPSubdivision_id", "label" => "Типо (Форма 30]", "rules" => "", "type" => "string"],
				["field" => "FPID", "label" => "Функциональное подразделение (СУР]", "rules" => "", "type" => "id"],
				["field" => "PalliativeType_id", "label" => "Вид отделения ПМП", "rules" => "", "type" => "id"],
				["field" => "FRMOUnit_id", "label" => "ФРМО Справочник структурных подразделений", "rules" => "", "type" => "id"],
				["field" => "FRMOSection_id", "label" => "ФРМО Справочник отделений и кабинетов", "rules" => "", "type" => "id"],
			],
			"saveLpuUnit" => [
				["field" => "DopNew", "label" => "Тип(доп.]", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_id", "label" => "Идентификатор группы отделений", "rules" => "", "type" => "id"],
				["field" => "LpuUnit_begDate", "label" => "Период действия: от", "rules" => "", "type" => "date"],
				["field" => "LpuUnit_endDate", "label" => "Период действия: до", "rules" => "", "type" => "date"],
				['field' => 'LpuUnit_Code', 'label' => 'Код группы отделений', 'rules' => 'required|is_numeric|is_natural_no_zero|max_length[5]', 'type' => 'string'],
				["field" => "LpuUnit_Name", "label" => "Наименование группы отделений", "rules" => "required", "type" => "string"],
				["field" => "LpuUnitType_id", "label" => "Тип группы отделений", "rules" => "required", "type" => "id"],
				["field" => "LpuUnitTypeDop_id", "label" => "Дополнительный тип группы отделений", "rules" => "", "type" => "id"],
				["field" => "LpuUnit_Phone", "label" => "Телефоны", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_Descr", "label" => "Примечание", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_Email", "label" => "Email", "rules" => "trim", "type" => "string"],
				["field" => "LpuUnit_IP", "label" => "IP адрес", "rules" => "trim", "type" => "string"],
				["field" => "LpuUnitSet_id", "label" => "Справочник", "rules" => "", "type" => "id"],
				["field" => "LpuBuilding_id", "label" => "Подразделение", "rules" => "", "type" => "id"],
				["field" => "LpuUnit_IsEnabled", "label" => "Включить запись операторами", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_isPallCC", "label" => "Признак центра паллиативной медицинской помощи (ПМП]", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_IsOMS", "label" => "Флаг работы по ОМС", "rules" => "", "type" => "checkbox"],
				["field" => "LpuUnitProfile_fid", "label" => "Тип (ФРМО]", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_isStandalone", "label" => "Обособленность", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_isCMP", "label" => "Прием скорой помощи", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_isHomeVisit", "label" => "Прием на дом", "rules" => "", "type" => "string"],
				["field" => "UnitDepartType_fid", "label" => "Прием на дом", "rules" => "", "type" => "string"],
				["field" => "LpuBuildingPass_id", "label" => "Основное здание", "rules" => "", "type" => "string"],
				["field" => "FRMOUnit_id", "label" => "ФРМО Справочник структурных подразделений", "rules" => "", "type" => "id"],
				["field" => "ignoreFRMOUnitCheck", "label" => "Признак игнорирования проверки", "rules" => "", "type" => "id"],
			],
			"getLpuRegionListByName" => [
				["field" => "LpuBuilding_id", "label" => "Идентификатор подразделения", "rules" => "required", "type" => "id"],
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "required", "type" => "id"],
				["field" => "LpuRegion_Name", "label" => "Номер участка", "rules" => "required", "type" => "string"]
			],
			"getLpuRegionListByMO" => [
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "required", "type" => "id", "equalsession" => true],
			],
			"createLpuRegion" => [
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "required", "type" => "id", "equalsession" => true],
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "required", "type" => "id"],
				["field" => "LpuBuilding_id", "label" => "Идентификатор подразделения", "rules" => "required", "type" => "id"],
				["field" => "LpuRegionType_id", "label" => "Тип участка", "rules" => "required", "type" => "id"],
				["field" => "LpuRegion_Name", "label" => "Номер участка", "rules" => "required", "type" => "string"],
				["field" => "LpuRegion_begDate", "label" => "Дата создания", "rules" => "required", "type" => "date"],
				["field" => "LpuRegion_endDate", "label" => "Дата закрытия", "rules" => "", "type" => "date"]
			],
			"updateLpuRegion" => [
				["field" => "LpuRegion_id", "label" => "Идентификатор участка", "rules" => "required", "type" => "id"],
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "", "type" => "id"],
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "", "type" => "id"],
				["field" => "LpuBuilding_id", "label" => "Идентификатор подразделения", "rules" => "", "type" => "id"],
				["field" => "LpuRegionType_id", "label" => "Тип участка", "rules" => "", "type" => "id"],
				["field" => "LpuRegion_Name", "label" => "Номер участка", "rules" => "", "type" => "string"],
				["field" => "LpuRegion_begDate", "label" => "Дата создания", "rules" => "", "type" => "date"],
				["field" => "LpuRegion_endDate", "label" => "Дата закрытия", "rules" => "", "type" => "date"]
			],
			"createLpuRegionWorkerPlace" => [
				["field" => "LpuRegion_id", "label" => "Идентификатор участка", "rules" => "required", "type" => "id"],
				["field" => "MedStaffFact_id", "label" => "Идентификатор места работы сотрудника", "rules" => "required", "type" => "id"],
				["field" => "MedStaffRegion_begDate", "label" => "Дата начала периода", "rules" => "required", "type" => "date"],
				["field" => "MedStaffRegion_endDate", "label" => "Дата окончания периода", "rules" => "", "type" => "date"],
				["field" => "MedStaffRegion_isMain", "label" => "Признак основного врача на участке", "rules" => "required", "type" => "api_flag"]
			],
			"updateLpuRegionWorkerPlace" => [
				["field" => "MedStaffRegion_id", "label" => "Идентификатор периода работы врача на участке", "rules" => "required", "type" => "id"],
				["field" => "MedStaffFact_id", "label" => "Идентификатор места работы сотрудника", "rules" => "", "type" => "id"],
				["field" => "MedStaffRegion_begDate", "label" => "Дата начала периода", "rules" => "", "type" => "date"],
				["field" => "MedStaffRegion_endDate", "label" => "Дата окончания периода", "rules" => "", "type" => "date"],
				["field" => "MedStaffRegion_isMain", "label" => "Признак основного врача на участке", "rules" => "", "type" => "api_flag"]
			],
			"updateLpuSection" => [
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "required", "type" => "id"],
				["field" => "LpuSection_setDate", "label" => "Дата создания отделения", "rules" => "", "type" => "date"],
				["field" => "LpuSection_disDate", "label" => "Дата закрытия отделения", "rules" => "", "type" => "date"],
				["field" => "LpuSectionProfile_Code", "label" => "Код профиля отделения", "rules" => "", "type" => "string"],
				["field" => "LpuUnit_id", "label" => "Идентификатор группы отделений", "rules" => "required", "type" => "id"],
				["field" => "LpuSection_Code", "label" => "Код отделения", "rules" => "", "type" => "string"],
				["field" => "LpuSectionCode_id", "label" => "Код отделения", "rules" => "", "type" => "id"],
				["field" => "LpuSection_Name", "label" => "Наименование отделения", "rules" => "", "type" => "string"],
				["field" => "MesAgeGroup_id", "label" => "Идентификатор фозрастной группы", "rules" => "", "type" => "id"],
				["field" => "MESLevel_id", "label" => "Идентификатор уровня МЭС", "rules" => "", "type" => "id"],
				["field" => "LpuSection_IsHTMedicalCare", "label" => "Флаг выполненеия ВМП", "rules" => "", "type" => "api_flag"],
				["field" => "LpuSection_KolAmbul", "label" => "Количество бригад скорой помощи", "rules" => "", "type" => "int"],
				["field" => "LpuSection_KolJob", "label" => "Количество рабочих мест", "rules" => "", "type" => "int"],
				["field" => "LpuSection_PlanAutopShift", "label" => "Плановое число вскрытий за смену", "rules" => "", "type" => "int"],
				["field" => "LpuSection_PlanResShift", "label" => "Плановое число исследований в смену", "rules" => "", "type" => "int"],
				["field" => "LpuSection_PlanTrip", "label" => "Плановое число выездов в смену", "rules" => "", "type" => "int"],
				["field" => "LpuSection_PlanVisitDay", "label" => "Плановое число посещений в сутки", "rules" => "", "type" => "int"],
				["field" => "LpuSection_PlanVisitShift", "label" => "Плановое число посещений в смену", "rules" => "", "type" => "int"],
				["field" => "LpuSectionAge_id", "label" => "Идентификатор типа отделения по возрасту", "rules" => "", "type" => "id"],
				["field" => "LpuSectionBedProfile_id", "label" => "Идентификатор профиля коек", "rules" => "", "type" => "id"],
				["field" => "LpuSectionOuter_id", "label" => "Идентификатор отделения МО в сторонеей МИС", "rules" => "", "type" => "id"],
				["field" => "FRMPSubdivision_id", "label" => "Код типа отделения (по ФРМР] для формы 30", "rules" => "required", "type" => "id"],
				["field" => "LpuBuildingPass_id", "label" => "Идентификатор здания МО", "rules" => "", "type" => "id"],
			],
			"updateLpuSectionDopProfile" => [
				["field" => "LpuSectionLpuSectionProfile_id", "label" => "Идентификатор дополнительного профиля отделения", "rules" => "required", "type" => "id"],
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "", "type" => "id"],
				["field" => "LpuSectionProfile_id", "label" => "Идентификатор профиля отделения", "rules" => "", "type" => "id"],
				["field" => "LpuSectionLpuSectionProfile_begDate", "label" => "Дата начала действия дополнительного профиля отделения", "rules" => "", "type" => "date"],
				["field" => "LpuSectionLpuSectionProfile_endDate", "label" => "Дата окончания действия дополнительного профиля отделения", "rules" => "", "type" => "date"],
			],
			"createLpuSectionWard" => [
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionWard_Name", "label" => "Наименование (номер] палаты", "rules" => "required", "type" => "string"],
				["field" => "LpuSectionWard_Floor", "label" => "Этаж", "rules" => "required", "type" => "string"],
				["field" => "LpuWardType_id", "label" => "Тип палаты", "rules" => "required", "type" => "id"],
				["field" => "Sex_id", "label" => "Вид палаты", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionWard_MainPlace", "label" => "Количество основных мест в палате", "rules" => "", "type" => "int"],
				["field" => "LpuSectionWard_DopPlace", "label" => "Количество дополнительных мест в палате", "rules" => "", "type" => "int"],
				["field" => "LpuSectionWard_BedRepair", "label" => "Количество коек на ремонте", "rules" => "", "type" => "int", "default" => 0],
				["field" => "LpuSectionWard_Square", "label" => "Площадь палаты", "rules" => "", "type" => "int"],
				["field" => "LpuSectionWard_DayCost", "label" => "Стоимость нахождения в сутки", "rules" => "", "type" => "float", "default" => 0],
				["field" => "LpuSectionWard_Views", "label" => "Вид из окна", "rules" => "", "type" => "string"],
				["field" => "LpuSectionWard_setDate", "label" => "Дата начала периода действия", "rules" => "required", "type" => "date"],
				["field" => "LpuSectionWard_disDate", "label" => "Дата окончания периода действия", "rules" => "", "type" => "date"],
			],
			"updateLpuSectionWard" => [
				["field" => "LpuSectionWard_id", "label" => "Идентификатор палаты", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionWard_Name", "label" => "Наименование (номер] палаты", "rules" => "", "type" => "string"],
				["field" => "LpuSectionWard_Floor", "label" => "Этаж", "rules" => "required", "type" => "string"],
				["field" => "LpuWardType_id", "label" => "Тип палаты", "rules" => "", "type" => "id"],
				["field" => "Sex_id", "label" => "Вид палаты", "rules" => "", "type" => "id"],
				["field" => "LpuSectionWard_MainPlace", "label" => "Количество основных мест в палате", "rules" => "", "type" => "int"],
				["field" => "LpuSectionWard_DopPlace", "label" => "Количество дополнительных мест в палате", "rules" => "", "type" => "int"],
				["field" => "LpuSectionWard_BedRepair", "label" => "Количество коек на ремонте", "rules" => "", "type" => "int", "default" => 0],
				["field" => "LpuSectionWard_Square", "label" => "Площадь палаты", "rules" => "", "type" => "int"],
				["field" => "LpuSectionWard_DayCost", "label" => "Стоимость нахождения в сутки", "rules" => "", "type" => "float", "default" => 0],
				["field" => "LpuSectionWard_Views", "label" => "Вид из окна", "rules" => "", "type" => "string"],
				["field" => "LpuSectionWard_setDate", "label" => "Дата начала периода действия", "rules" => "", "type" => "date"],
				["field" => "LpuSectionWard_disDate", "label" => "Дата окончания периода действия", "rules" => "", "type" => "date"],
			],
			"deleteLpuSectionWard" => [
				["field" => "LpuSectionWard_id", "label" => "Идентификатор палаты", "rules" => "required", "type" => "id"],
			],
			"getLpuSectionWardListByName" => [
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionWard_Name", "label" => "Наименование (номер] палаты", "rules" => "required", "type" => "string"],
			],
			"getLpuSectionWardListBySection" => [
				["field" => "LpuSection_id", "label" => "Идентификатор отделения", "rules" => "required", "type" => "id"],
			],
			"getLpuSectionWardById" => [
				["field" => "LpuSectionWard_id", "label" => "Идентификатор палаты", "rules" => "required", "type" => "id"],
			],
			"createLpuSectionWardComfortLink" => [
				["field" => "LpuSectionWard_id", "label" => "Идентификатор палаты", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionWardComfortLink_Count", "label" => "Количество объектов", "rules" => "required", "type" => "int"],
				["field" => "DChamberComfort_id", "label" => " Наименование объекта", "rules" => "required", "type" => "id"],
			],
			"updateLpuSectionWardComfortLink" => [
				["field" => "LpuSectionWardComfortLink_id", "label" => "Идентификатор объекта комфорта в палате", "rules" => "required", "type" => "id"],
				["field" => "LpuSectionWardComfortLink_Count", "label" => "Количество объектов", "rules" => "", "type" => "int"],
				["field" => "DChamberComfort_id", "label" => " Наименование объекта", "rules" => "", "type" => "id"],
			],
			"deleteLpuSectionWardComfortLink" => [
				["field" => "LpuSectionWardComfortLink_id", "label" => "Идентификатор объекта комфорта в палате", "rules" => "required", "type" => "id"],
			],
			"getLpuSectionWardComfortLinkByName" => [
				["field" => "LpuSectionWard_id", "label" => "Идентификатор палаты", "rules" => "required", "type" => "id"],
				["field" => "DChamberComfort_id", "label" => " Наименование объекта", "rules" => "required", "type" => "id"],
			],
			"getLpuSectionWardComfotLinkListByWard" => [
				["field" => "LpuSectionWard_id", "label" => "Идентификатор палаты", "rules" => "required", "type" => "id"],
			],
			"getMOById" => [
				["field" => "Lpu_id", "label" => "Идентификатор МО", "rules" => "required", "type" => "id"],
			],
		];
	}
}