Ext6.define('usluga.common.models.UslugaFormModel', {
	extend: 'Ext6.data.Model',
	alias: 'model.UslugaFormModel',
	idProperty: 'EvnUslugaCommon_id',
	fields: [
		{ name: 'accessType' },
		{ name: 'EvnPrescr_id' },
		{ name: 'EvnDirection_id' },
		{ name: 'EvnUslugaCommon_id' },
		{ name: 'EvnUslugaCommon_Kolvo' },
		{ name: 'EvnUslugaCommon_pid' },
		{ name: 'EvnUslugaCommon_Price' },
		{ name: 'EvnUslugaCommon_rid' },
		{ name: 'EvnUslugaCommon_setDate', type: 'date', dateFormat: 'd.m.Y' },
		{ name: 'EvnUslugaCommon_setTime' },
		{ name: 'EvnUslugaCommon_disDate', type: 'date', dateFormat: 'd.m.Y' },
		{ name: 'EvnUslugaCommon_disTime' },
		{ name: 'EvnUslugaCommon_Summa' },
		{ name: 'Lpu_uid' },
		{ name: 'LpuSection_uid' },
		{ name: 'MedPersonal_id' },
		{ name: 'MedStaffFact_id' },
		{ name: 'Morbus_id' },
		{ name: 'Org_uid' },
		{ name: 'PayType_id' },
		{ name: 'Person_id' },
		{ name: 'PersonEvn_id' },
		{ name: 'Server_id' },
		{ name: 'UslugaComplex_id' },
		{ name: 'UslugaCategory_id' },
		{ name: 'UslugaComplexTariff_id' },
		{ name: 'UslugaComplexTariff_UED' },
		{ name: 'DiagSetClass_id' },
		{ name: 'Diag_id' },
		{ name: 'UslugaPlace_id' },
		{ name: 'EvnUslugaOnkoBeam_disDT', type: 'date', dateFormat: 'd.m.Y' },
		{ name: 'OnkoUslugaBeamIrradiationType_id' },
		{ name: 'OnkoUslugaBeamKindType_id' },
		{ name: 'OnkoUslugaBeamMethodType_id' },
		{ name: 'OnkoUslugaBeamRadioModifType_id' },
		{ name: 'OnkoUslugaBeamFocusType_id' },
		{ name: 'EvnUslugaOnkoBeam_TotalDoseTumor' },
		{ name: 'EvnUslugaOnkoBeam_TotalDoseRegZone' },
		{ name: 'OnkoUslugaBeamUnitType_id' },
		{ name: 'OnkoUslugaBeamUnitType_did' },
		{ name: 'EvnUslugaOnkoChem_disDT', type: 'date', dateFormat: 'd.m.Y' },
		{ name: 'OnkoUslugaChemKindType_id' },
		{ name: 'OnkoUslugaChemFocusType_id' },
		{ name: 'EvnUslugaOnkoChem_Dose' },
		{ name: 'EvnUslugaOnkoGormun_setDT', type: 'date', dateFormat: 'd.m.Y' },
		{ name: 'EvnUslugaOnkoGormun_disDT', type: 'date', dateFormat: 'd.m.Y' },
		{ name: 'EvnUslugaOnkoGormun_IsDrug' },
		{ name: 'EvnUslugaOnkoGormun_IsSurgical' },
		{ name: 'EvnUslugaOnkoGormun_IsBeam' },
		{ name: 'OnkoUslugaGormunFocusType_id' },
		{ name: 'OnkoDrug_id' },
		{ name: 'LpuSectionProfile_id' },
		{ name: 'MedSpecOms_id' },
		{ name: 'EvnUslugaCommon_pid_Name' },
		{ name: 'EvnUslugaOnkoGormun_Dose' },
		{ name: 'EvnUslugaCommon_IsMinusUsluga' },
		{ name: 'UslugaExecutionType_id' },
		{ name: 'UslugaExecutionReason_id' }
	]
});