<Document version="2.0.1" id="0" xmlns="http://rosmintrud.ru/mse/eaviias/form88/180906" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://rosmintrud.ru/mse/eaviias/form88/180906 form88.v.2.0.1.xsd">
<G_Code>{G_Code}</G_Code>
	<TargetMseOrg>
		<Id>{TargetMseOrg/ID}</Id>
		<Value>{TargetMseOrg/Value}</Value>
	</TargetMseOrg>
	<Form id="88">
		<MedOrgName>{MedOrgName}</MedOrgName>
		<MedOrgAddress>{MedOrgAddress}</MedOrgAddress>
		<MedOrgTerritorySubject>
			<Id>{MedOrgTerritorySubject/ID}</Id>
			<Value>{MedOrgTerritorySubject/Value}</Value>
		</MedOrgTerritorySubject>
		<MedOrgOgrn>{MedOrgOgrn}</MedOrgOgrn>
		<ProtocolNum>{ProtocolNum}</ProtocolNum>
		<ProtocolDate>{ProtocolDate}</ProtocolDate>
		<MseMustBeAtHome>{MseMustBeAtHome}</MseMustBeAtHome>
		<PalliativeHelpNeeded>{PalliativeHelpNeeded}</PalliativeHelpNeeded>
		<IssueDate>{IssueDate}</IssueDate>
		<ExaminationPurposes>
			{ExaminationPurposes}
			<Purpose>
				<Id>{ExaminationPurposes/ID}</Id>
				<Value>{ExaminationPurposes/Value}</Value>
			</Purpose>
			{/ExaminationPurposes}
		</ExaminationPurposes>
		<ExaminationPurposesComment>{ExaminationPurposesComment}</ExaminationPurposesComment>
		<LastName>{LastName}</LastName>
		<FirstName>{FirstName}</FirstName>
		<SecondName>{SecondName}</SecondName>
		<BirthDate>{BirthDate}</BirthDate>
		<Age>
			<Years>{Age/Years}</Years>
			<Months>{Age/Months}</Months>
		</Age>
		<Gender>{Gender}</Gender>
		<Citizenship>
			<Id>{Citizenship/ID}</Id>
			<Value>{Citizenship/Value}</Value>
		</Citizenship>
		<MilitaryDuty>
			<Id>{MilitaryDuty/ID}</Id>
			<Value>{MilitaryDuty/Value}</Value>
		</MilitaryDuty>
		<AddressType>
			<Id>{AddressType/ID}</Id>
			<Value>{AddressType/Value}</Value>
		</AddressType>
		{Address}
		<Address>
			<ZipCode>{ZipCode}</ZipCode>
			<TerritorySubject>
				<Id>{TerritorySubject/ID}</Id>
				<Value>{TerritorySubject/Value}</Value>
			</TerritorySubject>
			<TerritorySubjectOther>{TerritorySubjectOther}</TerritorySubjectOther>
			<District>{District}</District>
			<Place>{Place}</Place>
			<Street>{Street}</Street>
			<Building>{Building}</Building>
			<Flat>{Flat}</Flat>
		</Address>
		{/Address}
		<HasNoLivingAddress>{HasNoLivingAddress}</HasNoLivingAddress>
		<PersonPlace>
			<PlaceType>
				<Id>{PersonPlace/PlaceType/ID}</Id>
				<Value>{PersonPlace/PlaceType/Value}</Value>
			</PlaceType>
			{PersonPlace/PlaceAddress}
			<PlaceAddress>
				<ZipCode>{ZipCode}</ZipCode>
				<TerritorySubject>
					<Id>{TerritorySubject/ID}</Id>
					<Value>{TerritorySubject/Value}</Value>
				</TerritorySubject>
				<TerritorySubjectOther>{TerritorySubjectOther}</TerritorySubjectOther>
				<District>{District}</District>
				<Place>{Place}</Place>
				<Street>{Street}</Street>
				<Building>{Building}</Building>
				<Flat>{Flat}</Flat>
			</PlaceAddress>
			{/PersonPlace/PlaceAddress}
			<PlaceOgrn>{PersonPlace/PlaceOgrn}</PlaceOgrn>
		</PersonPlace>
		<Phone>{Phone}</Phone>
		<Email>{Email}</Email>
		<Snils>{Snils}</Snils>
		<IdentityDoc>
			<IdentityCardTypeId>
				<Id>{IdentityDoc/IdentityCardTypeId/ID}</Id>
				<Value>{IdentityDoc/IdentityCardTypeId/Value}</Value>
			</IdentityCardTypeId>
			<Series>{IdentityDoc/Series}</Series>
			<Number>{IdentityDoc/Number}</Number>
			<IssueOrgName>{IdentityDoc/IssueOrgName}</IssueOrgName>
			<IssueDate>{IdentityDoc/IssueDate}</IssueDate>
		</IdentityDoc>
		<Representer>
			<LastName>{Representer/LastName}</LastName>
			<FirstName>{Representer/FirstName}</FirstName>
			<SecondName>{Representer/SecondName}</SecondName>
			<AuthorityDoc>
				<IdentityCardTypeId>
					<Id>{Representer/AuthorityDoc/IdentityCardTypeId/ID}</Id>
					<Value>{Representer/AuthorityDoc/IdentityCardTypeId/Value}</Value>
				</IdentityCardTypeId>
				<Series>{Representer/AuthorityDoc/Series}</Series>
				<Number>{Representer/AuthorityDoc/Number}</Number>
				<IssueOrgName>{Representer/AuthorityDoc/IssueOrgName}</IssueOrgName>
				<IssueDate>{Representer/AuthorityDoc/IssueDate}</IssueDate>
			</AuthorityDoc>
			<IdentityDoc>
				<IdentityCardTypeId>
					<Id>{Representer/IdentityDoc/IdentityCardTypeId/ID}</Id>
					<Value>{Representer/IdentityDoc/IdentityCardTypeId/Value}</Value>
				</IdentityCardTypeId>
				<Series>{Representer/IdentityDoc/Series}</Series>
				<Number>{Representer/IdentityDoc/Number}</Number>
				<IssueOrgName>{Representer/IdentityDoc/IssueOrgName}</IssueOrgName>
				<IssueDate>{Representer/IdentityDoc/IssueDate}</IssueDate>
			</IdentityDoc>
			<Phone>{Representer/Phone}</Phone>
			<Email>{Representer/Email}</Email>
			<Snils>{Representer/Snils}</Snils>
		</Representer>
		<RepresentativeOrg>
			<Name>{RepresentativeOrg/Name}</Name>
			{RepresentativeOrg/Address}
			<Address>
				<ZipCode>{ZipCode}</ZipCode>
				<TerritorySubject>
					<Id>{TerritorySubject/ID}</Id>
					<Value>{TerritorySubject/Value}</Value>
				</TerritorySubject>
				<TerritorySubjectOther>{TerritorySubjectOther}</TerritorySubjectOther>
				<District>{District}</District>
				<Place>{Place}</Place>
				<Street>{Street}</Street>
				<Building>{Building}</Building>
				<Flat>{Flat}</Flat>
			</Address>
			{/RepresentativeOrg/Address}
			<Ogrn>{RepresentativeOrg/Ogrn}</Ogrn>
		</RepresentativeOrg>
		<RepetitionKind>
			<Id>{RepetitionKind/ID}</Id>
			<Value>{RepetitionKind/Value}</Value>
		</RepetitionKind>
		<PrevExamInfo>
			<DisabilityGroup>
				<Id>{PrevExamInfo/DisabilityGroup/ID}</Id>
				<Value>{PrevExamInfo/DisabilityGroup/Value}</Value>
			</DisabilityGroup>
			<DisabilityEndDate>{PrevExamInfo/DisabilityEndDate}</DisabilityEndDate>
			<DisabilityPeriod>
				<Id>{PrevExamInfo/DisabilityPeriod/ID}</Id>
				<Value>{PrevExamInfo/DisabilityPeriod/Value}</Value>
			</DisabilityPeriod>
			<DisabilityReason>
				<Id>{PrevExamInfo/DisabilityReason/ID}</Id>
				<Value>{PrevExamInfo/DisabilityReason/Value}</Value>
			</DisabilityReason>
			<DisabilityReasonOther>{PrevExamInfo/DisabilityReasonOther}</DisabilityReasonOther>
			<DisabilityReasonOutdated>{PrevExamInfo/DisabilityReasonOutdated}</DisabilityReasonOutdated>
			<ProfLossDegree>{PrevExamInfo/ProfLossDegree}</ProfLossDegree>
			<ProfLossPeriod>
				<Id>{PrevExamInfo/ProfLossPeriod/ID}</Id>
				<Value>{PrevExamInfo/ProfLossPeriod/Value}</Value>
			</ProfLossPeriod>
			<ProfLossEndDate>{PrevExamInfo/ProfLossEndDate}</ProfLossEndDate>
			<ProfLossPreviousCases>{PrevExamInfo/ProfLossPreviousCases}</ProfLossPreviousCases>
		</PrevExamInfo>
		<EducationInfo>
			<OrgName>{EducationInfo/OrgName}</OrgName>
			{EducationInfo/OrgAddress}
			<OrgAddress>
				<ZipCode>{ZipCode}</ZipCode>
				<TerritorySubject>
					<Id>{TerritorySubject/ID}</Id>
					<Value>{TerritorySubject/Value}</Value>
				</TerritorySubject>
				<TerritorySubjectOther>{TerritorySubjectOther}</TerritorySubjectOther>
				<District>{District}</District>
				<Place>{Place}</Place>
				<Street>{Street}</Street>
				<Building>{Building}</Building>
				<Flat>{Flat}</Flat>
			</OrgAddress>
			{/EducationInfo/OrgAddress}
			<LevelType>
				<Id>{EducationInfo/LevelType/ID}</Id>
				<Value>{EducationInfo/LevelType/Value}</Value>
			</LevelType>
			<LevelValue>{EducationInfo/LevelValue}</LevelValue>
			<Profession>{EducationInfo/Profession}</Profession>
		</EducationInfo>
		<ProfInfo>
			<MainProfession>{ProfInfo/MainProfession}</MainProfession>
			<Qualification>{ProfInfo/Qualification}</Qualification>
			<JobExperience>{ProfInfo/JobExperience}</JobExperience>
			<CurrentJob>
				<Profession>{ProfInfo/CurrentJob/Profession}</Profession>
				<Speciality>{ProfInfo/CurrentJob/Speciality}</Speciality>
				<Position>{ProfInfo/CurrentJob/Position}</Position>
			</CurrentJob>
			<LaborConditions>{ProfInfo/LaborConditions}</LaborConditions>
			<JobPlace>{ProfInfo/JobPlace}</JobPlace>
			<JobAddress>
			{ProfInfo/JobAddress}
				<ZipCode>{ZipCode}</ZipCode>
				<TerritorySubject>
					<Id>{TerritorySubject/ID}</Id>
					<Value>{TerritorySubject/Value}</Value>
				</TerritorySubject>
				<TerritorySubjectOther>{TerritorySubjectOther}</TerritorySubjectOther>
				<District>{District}</District>
				<Place>{Place}</Place>
				<Street>{Street}</Street>
				<Building>{Building}</Building>
				<Flat>{Flat}</Flat>
			{/ProfInfo/JobAddress}
			</JobAddress>
		</ProfInfo>
		<MedOrgSupervisionStartYear>{MedOrgSupervisionStartYear}</MedOrgSupervisionStartYear>
		<DeseaseAnamnesis>{DeseaseAnamnesis}</DeseaseAnamnesis>
		<LifeAnamnesis>{LifeAnamnesis}</LifeAnamnesis>
		<TempWorkDisabilityItems>
			{TempWorkDisabilityItems/Item}
			<Item>
				<StartDate>{StartDate}</StartDate>
				<EndDate>{EndDate}</EndDate>
				<DaysCount>{DaysCount}</DaysCount>
				<Diagnosis>{Diagnosis}</Diagnosis>
			</Item>
			{/TempWorkDisabilityItems/Item}
		</TempWorkDisabilityItems>
		<HasEln>{HasEln}</HasEln>
		<ElnNum>{ElnNum}</ElnNum>
		<RehabEventsResult>
			<IpraNum>{RehabEventsResult/IpraNum}</IpraNum>
			<ProtocolNum>{RehabEventsResult/ProtocolNum}</ProtocolNum>
			<ProtocolDate>{RehabEventsResult/ProtocolDate}</ProtocolDate>
			<ImpairedFunctionsRecovery>
				<Id>{RehabEventsResult/ImpairedFunctionsRecovery/ID}</Id>
				<Value>{RehabEventsResult/ImpairedFunctionsRecovery/Value}</Value>
			</ImpairedFunctionsRecovery>
			<LostFunctionsCompensation>
				<Id>{RehabEventsResult/LostFunctionsCompensation/ID}</Id>
				<Value>{RehabEventsResult/LostFunctionsCompensation/Value}</Value>
			</LostFunctionsCompensation>
			<Comment>{RehabEventsResult/Comment}</Comment>
		</RehabEventsResult>
		<AnthropometricData>
			<Height>{AnthropometricData/Height}</Height>
			<Weight>{AnthropometricData/Weight}</Weight>
			<BMI>{AnthropometricData/BMI}</BMI>
			<Constitution>{AnthropometricData/Constitution}</Constitution>
			<PhysiologicalFunctionsDailyAmmount>{AnthropometricData/PhysiologicalFunctionsDailyAmmount}</PhysiologicalFunctionsDailyAmmount>
			<WaistSize>{AnthropometricData/WaistSize}</WaistSize>
			<HipsVolume>{AnthropometricData/HipsVolume}</HipsVolume>
			<BirthWeight>{AnthropometricData/BirthWeight}</BirthWeight>
			<PhysicalDevelopment>{AnthropometricData/PhysicalDevelopment}</PhysicalDevelopment>
		</AnthropometricData>
		<HealthCondition>{HealthCondition}</HealthCondition>
		<RequiredMedExams>{RequiredMedExams}</RequiredMedExams>
		<Diagnosis>
			<MainDesease>{Diagnosis/MainDesease}</MainDesease>
			<MainDeseaseCode>{Diagnosis/MainDeseaseCode}</MainDeseaseCode>
			<MainDeseaseComplications>{Diagnosis/MainDeseaseComplications}</MainDeseaseComplications>
			<AccompanyingDiseases>{Diagnosis/AccompanyingDiseases}</AccompanyingDiseases>
			<AccompanyingDiseasesCodes>
				{Diagnosis/AccompanyingDiseasesCodes}
				<Code>{Code}</Code>
				{/Diagnosis/AccompanyingDiseasesCodes}
			</AccompanyingDiseasesCodes>
			<AccompanyingDiseasesComplications>{Diagnosis/AccompanyingDiseasesComplications}</AccompanyingDiseasesComplications>
		</Diagnosis>
		<ClinicalPrognosis>
			<Id>{ClinicalPrognosis/ID}</Id>
			<Value>{ClinicalPrognosis/Value}</Value>
		</ClinicalPrognosis>
		<RehabPotential>
			<Id>{RehabPotential/ID}</Id>
			<Value>{RehabPotential/Value}</Value>
		</RehabPotential>
		<RehabPrognosis>
			<Id>{RehabPrognosis/ID}</Id>
			<Value>{RehabPrognosis/Value}</Value>
		</RehabPrognosis>
		<RecommendedMedEvents>{RecommendedMedEvents}</RecommendedMedEvents>
		<RecommendedReconstructiveSurgeryEvents>{RecommendedReconstructiveSurgeryEvents}</RecommendedReconstructiveSurgeryEvents>
		<RecommendedProstheticsEvents>{RecommendedProstheticsEvents}</RecommendedProstheticsEvents>
		<SpaTreatment>{SpaTreatment}</SpaTreatment>
		<MedCommissionChairman>{MedCommissionChairman}</MedCommissionChairman>
		<MedCommissionMembers>
			{MedCommissionMembers}
			<Person>{Person}</Person>
			{/MedCommissionMembers}
		</MedCommissionMembers>
	</Form>
</Document>