<REGISTR_DOC>
{omsDoctor}
<omsDoctor>
	<mcod>{mcod}</mcod>
	<IDDOKT>{IDDOKT}</IDDOKT>
	<Famil>{Famil}</Famil>
	<NAME>{NAME}</NAME>
	<Ot>{Ot}</Ot>
	<SNILS>{SNILS}</SNILS>
	<LPU_1>{LPU_1}</LPU_1>
	<PR_VR>{PR_VR}</PR_VR>
	<Middle_VR>{Middle_VR}</Middle_VR>
	<Profil>{Profil}</Profil>
	<DateBeg>{DateBeg}</DateBeg>
	<Docum>{Docum}</Docum>
	<SpecSert>{SpecSert}</SpecSert>
	<SerSert>{SerSert}</SerSert>
	<NumSert>{NumSert}</NumSert>
	<Sert_DN>{Sert_DN}</Sert_DN>
</omsDoctor>
{/omsDoctor}
</REGISTR_DOC>