<PERSONATTACH>
	<HEADER>
		{OPERATIONTYPE}
		{CODE_MO}
		{PERSONATTACHID}
	</HEADER>
	<?php if($OPERATIONTYPE!='Delete'){ ?><BODY>
		{BDZID}
		{LPUREGION_ID}
		{LPUREGIONFAP_ID}
		{PERSONATTACHDATE}
		{PERSONATTACHENDT}
		{PERSONATTACHUSL}
		{CARDCLSECAUSE}
	</BODY><?php } ?>
</PERSONATTACH>