<HTMC_REFERRAL>
	<HEADER>
		{OPERATIONTYPE}
		{DATA}
		{CODE_MO}
		{CODE_MO_TO}
		{HTMC_ID}
	</HEADER>
	<?php if($OPERATIONTYPE!='Delete'){ ?><BODY>
		{BDZ_ID}
		{REFERRAL_NUMBER}
		{REFERRAL_DATE}
		{TALON_NUMBER}
		{TALON_DATE}
		{DOC_CODE}
		{HTCCLASS}
		{PROTNUM}
		{PROTDATE}
		{PROTCOMMENT}
		{HTMCCOMMENT}
	</BODY><?php } ?>
</HTMC_REFERRAL>