<zl_list>
<zglv>
	<filename>{filename}</filename>
	<version>1.0</version>
	<data>{data}</data>
	<codmof>{codmof}</codmof>
	<dn>{dn}</dn>
	<dk>{dk}</dk>
	<dt_report>{dt_report}</dt_report>
	<nfile>{nfile}</nfile>
	<nrec>{nrec}</nrec>
</zglv>
