{zl}<zl>
	<nomer_z>{nomer_z}</nomer_z>
	<Enp>{Enp}</Enp>
	<fam>{fam}</fam>
	<im>{im}</im>
	<ot>{ot}</ot>
	<dr>{dr}</dr>
	<w>{w}</w>
	<doctype>{doctype}</doctype>
	<docser>{docser}</docser>
	<docnum>{docnum}</docnum>
	<snils>{snils}</snils>
	<vpolis>{vpolis}</vpolis>
	<spolis>{spolis}</spolis>
	<npolis>{npolis}</npolis>
	<codmof>{codmof}</codmof>
	<attach_type>{attach_type}</attach_type>
	<attach_dt_mo>{attach_dt_mo}</attach_dt_mo>
	<detach_codmof>{detach_codmof}</detach_codmof>
	<detach_dt_mo>{detach_dt_mo}</detach_dt_mo>
	<detach_mo_cause>{detach_mo_cause}</detach_mo_cause>
	<cod_podr>{cod_podr}</cod_podr>
	<cod_otd>{cod_otd}</cod_otd>
	<cod_uch>{cod_uch}</cod_uch>
	<cod_pun>{cod_pun}</cod_pun>
	<typed_vr1>{typed_vr1}</typed_vr1>
	<snils_vr1>{snils_vr1}</snils_vr1>
	<attach_dt_vr1>{attach_dt_vr1}</attach_dt_vr1>
	<cod_podr_f>{cod_podr_f}</cod_podr_f>
	<cod_otd_f>{cod_otd_f}</cod_otd_f>
	<cod_uch_f>{cod_uch_f}</cod_uch_f>
	<cod_pun_f>{cod_pun_f}</cod_pun_f>
	<typed_vr2>{typed_vr2}</typed_vr2>
	<snils_vr2>{snils_vr2}</snils_vr2>
	<attach_dt_vr2>{attach_dt_vr2}</attach_dt_vr2>
	<detach_dt_vr2>{detach_dt_vr2}</detach_dt_vr2>
	<detach_vr2_cause>{detach_vr2_cause}</detach_vr2_cause>
</zl>{/zl}
