{zl}<zl>
	<nomer_z>{nomer_z}</nomer_z>
	<Enp>{Enp}</Enp>
	<fam>{fam}</fam>
	<im>{im}</im>
	<ot>{ot}</ot>
	<dr>{dr}</dr>
	<w>{w}</w>
	<doctype>{doctype}</doctype>
	<docser>{docser}</docser>
	<docnum>{docnum}</docnum>
	<snils>{snils}</snils>
	<vpolis>{vpolis}</vpolis>
	<spolis>{spolis}</spolis>
	<npolis>{npolis}</npolis>
	<codmof_disp>{codmof_disp}</codmof_disp>
	<attach_disp_type>{attach_disp_type}</attach_disp_type>
	<attach_disp_dt>{attach_disp_dt}</attach_disp_dt>
	<attach_disp_ds>{attach_disp_ds}</attach_disp_ds>
	<detach_disp_dt>{detach_disp_dt}</detach_disp_dt>
</zl>{/zl}
