	{ZAP}
	<ZAP>
		<N_ZAP>{N_ZAP}</N_ZAP>
		<PR_NOV>{PR_NOV}</PR_NOV>
		{PACIENT}
		<PACIENT>
			{ID_PAC}
			{VPOLIS}
			{SPOLIS}
			{NPOLIS}
			{ST_OKATO}
			{SMO}
			{SMO_OGRN}
			{SMO_OK}
			{SMO_NAM}
			{INV}
			{MSE}
			{NOVOR}
			{VNOV_D}
		</PACIENT>
		{/PACIENT}
		<Z_SL>
			{IDCASE}
			{USL_OK}
			{VIDPOM}
			{FOR_POM}
			{NPR_MO}
			{NPR_DATE}
			{P_DISP2}
			{LPU}
			{VBR}
			{DATE_Z_1}
			{DATE_Z_2}
			{KD_Z}
			{P_OTK}
			{VNOV_M_DATA}
			{VNOV_M_VAL}
			{/VNOV_M_DATA}
			{RSLT}
			{RSLT_D}
			{ISHOD}
			{OS_SLUCH_DATA}
			{OS_SLUCH}
			{/OS_SLUCH_DATA}
			{VB_P}
			{IDSP}
			{SUMV}
			{OPLATA}
			{SUMP}
			{SANK_IT}
			{SL}
			<SL>
				{SL_ID}
				{VID_HMP}
				{METOD_HMP}
				{LPU_1}
				{SL_PODR}
				{PROFIL_R}
				{PROFIL}
				{PROFIL_K}
				{DET}
				{TAL_D}
				{TAL_NUM}
				{TAL_P}
				{P_CEL}
				{NHISTORY}
				{P_PER}
				{DATE_1}
				{DATE_2}
				{KD}
				{DS0}
				{DS1}
				{DS1_PR}
				{DS2_DATA}
				{DS2}
				{/DS2_DATA}
				{DS3_DATA}
				{DS3}
				{/DS3_DATA}
				{C_ZAB}
				{DS_ONK}
				{PR_D_N}
				{DN}
				{TIME_MP}
				{KRAT_MP}
				{VISIT}
				{CODE_MES1_DATA}
				{CODE_MES1}
				{/CODE_MES1_DATA}
				{CODE_MES2}
				{REAB}
				{PRVS_R}
				{PRVS}
				{VERS_SPEC}
				{IDDOKT}
				{ED_COL}
				{TARIF_R}
				{TARIF}
				{SUM_M}
				{COMENTSL}
				{DS2_N_DATA}
				<DS2_N>
					{DS2}
					{DS2_PR}
					{PR_DS2_N}
				</DS2_N>
				{/DS2_N_DATA}
				{NAZ_DATA}
				<NAZ>
					{NAZ_N}
					{NAZ_R}
					{NAZ_SP}
					{NAZ_V}
					{NAZ_USL}
					{NAPR_DATE}
					{NAPR_MO}
					{NAZ_PMP}
					{NAZ_PK}
				</NAZ>
				{/NAZ_DATA}
				{NAPR_DATA}
				<NAPR>
					{NAPR_DATE}
					{NAPR_MO}
					{NAPR_V}
					{MET_ISSL}
					{NAPR_USL}
				</NAPR>
				{/NAPR_DATA}
				{CONS_DATA}
				<CONS>
					{PR_CONS}
					{DT_CONS}
				</CONS>
				{/CONS_DATA}
				{ONK_SL_DATA}
				<ONK_SL>
					{DS1_T}
					{STAD}
					{ONK_T}
					{ONK_N}
					{ONK_M}
					{MTSTZ}
					{SOD}
					{K_FR}
					{WEI}
					{HEI}
					{BSA}
					{B_DIAG_DATA}
					<B_DIAG>
						{DIAG_DATE}
						{DIAG_TIP}
						{DIAG_CODE}
						{DIAG_RSLT}
						{REC_RSLT}
					</B_DIAG>
					{/B_DIAG_DATA}
					{B_PROT_DATA}
					<B_PROT>
						{PROT}
						{D_PROT}
					</B_PROT>
					{/B_PROT_DATA}
					{ONK_USL_DATA}
					<ONK_USL>
						{USL_TIP}
						{HIR_TIP}
						{LEK_TIP_L}
						{LEK_TIP_V}
						{LUCH_TIP}
						{PPTR}
						{LEK_PR_DATA}
						<LEK_PR>
							{REGNUM}
							{CODE_SH}
							{DATE_INJ_DATA}
							{DATE_INJ}
							{/DATE_INJ_DATA}
						</LEK_PR>
						{/LEK_PR_DATA}
					</ONK_USL>
					{/ONK_USL_DATA}
				</ONK_SL>
				{/ONK_SL_DATA}
				{KSG_KPG_DATA}
				<KSG_KPG>
					{N_KSG}
					{VER_KSG}
					{KSG_PG}
					{N_KPG}
					{KOEF_Z}
					{KOEF_UP}
					{BZTSZ}
					{KOEF_D}
					{KOEF_U}
					{CRIT_DATA}
					{CRIT}
					{/CRIT_DATA}
					{SL_K}
					{IT_SL}
					{SL_KOEF_DATA}
					<SL_KOEF>
						{IDSL}
						{Z_SL}
					</SL_KOEF>
					{/SL_KOEF_DATA}
				</KSG_KPG>
				{/KSG_KPG_DATA}
				{USL}
				<USL>
					{IDSERV}
					{LPU_USL}
					{LPU_1_USL}
					{PODR_USL}
					{PROFIL_USL}
					{VID_VME}
					{DET_USL}
					{DATE_IN}
					{DATE_OUT}
					{P_OTK_USL}
					{DS}
					{CODE_USL}
					{KOL_USL}
					{TARIF_USL}
					{SUMV_USL}
					{PRVS_USL}
					{CODE_MD}
					{NPL}
					{COMENTU}
				</USL>
				{/USL}
			</SL>
			{/SL}
		</Z_SL>
	</ZAP>
	{/ZAP}
