	{PACIENT}
	<PERS>
		<ID_PAC>{ID_PAC}</ID_PAC>
		<FAM>{FAM}</FAM>
		<IM>{IM}</IM>
		<OT>{OT}</OT>
		<W>{W}</W>
		<DR>{DR}</DR>
		<FAM_P></FAM_P>
		<IM_P></IM_P>
		<OT_P></OT_P>
		<W_P></W_P>
		<DR_P></DR_P>
		<MR></MR>
		<DOCTYPE></DOCTYPE>
		<DOCSER></DOCSER>
		<DOCNUM></DOCNUM>
		<SNILS></SNILS>
		<OKATOG></OKATOG>
		<OKATOP></OKATOP>
		<COMENTP>{COMENTP}</COMENTP>
	</PERS>  
	{/PACIENT}
