<Root>
	<Header>
		{Version}
		{Date}
	</Header>
	{ZAP}
	<ZAP>
		{N_ZAP}
		{Patient}
		<Patient>
			{Last_Name}
			{First_Name}
			{Midd_Name}
			{Sex}
			{Birth_Date_Day}
			{Birth_Date_Mon}
			{Birth_Date_Year}
			{Perm_Addr}
			{Area_Type}
			{Oms_Pol}
			{Snils}
			{Smo_Tit}
			{Id_Type}
			{Id_Ser_Num}
			{Disp_Dis}
			{Disability}
			{Work_Loc}
			{Addr_Change}
			{Diag_List}
			{Blood_Type}
			{Rh_Type}
			{Inf_Consent_Data}
			{Inf_Cons_Med_Int}
			{Refusal}
			{Binding}
		</Patient>
		{/Patient}
		{Medical_Record}
		<Medical_Record>
			{Med_Card_Num}
			{TAP_Num}
			{Tap_Date_Op}
			<Pat_Priv>
				{Priv_Cat}
				{Exp_Date}
			</Pat_Priv>
			{Med_Care_Type}
			{Obj_Treat}
			{Fin_Case}
			{Mult_Treat}
			{Res_Treat}
			{Phys_Reff}
			{Visit}
			<Visit>
				{Visit_Date}
				{Visit_Nat}
				{Visit_Place}
				{Phys_ID}
				{Phys_Name}
				{Phys_Spec}
				<Diagnosis>
					{Diag_Type}
					{Diag_Sub_Type}
					{Diag_Div}
					{Diag_ID}
					{Diag_Tit}
					{Diag_FirstTime}
				</Diagnosis>
				<Service>
					{Service_ID}
					{Service_Tit}
					{Service_Quant}
					{Phys_ID}
					{Phys_Name}
					{Phys_Spec}
				</Service>
				<Surgery>
					{Surg_ID}
					{Surg_Tit}
					{Anest_Tit}
					{Equip_Tit}
					{Phys_ID}
					{Phys_Name}
					{Phys_Spec}
				</Surgery>
				<Studies>
					{Stud_ID}
					{Stud_Tit}
					{Stud_Quant}
					{Phys_ID}
					{Phys_Name}
					{Phys_Spec}
				</Studies>
				<Anamnesis>
					{Type}
					{Record}
				</Anamnesis>
				<Phys_Rec>
					{Rec_Date}
					{Compl}
					<Anamnesis>
						{Type}
						{Record}
					</Anamnesis>
					{Obj_Stat}
					{Loc_Stat}
					{CaseMonitoring}
					{Protocol}
					{Appointment}
					{Prescription}
					{Conclusion}
					{Recomm}
					{Plan}
					{Treatment}
					{Aux}
					{Diag_Diff}
					{Diag_Subst}
					{Next_Visit_Date}
					<Diagnosis>
						{Diag_Type}
						{Diag_Sub_Type}
						{Diag_Div}
						{Diag_ID}
						{Diag_Tit}
						{Diag_FirstTime}
					</Diagnosis>
				</Phys_Rec>
				<Epicrisis>
					{Date}
					{Type}
					{Compl}
					<Anamnesis>
						{Type}
						{Record}
					</Anamnesis>
					{Dyn_Obj_Stat}
					{Dyn_Loc_Stat}
					{Epicrisis}
					{Treat}
					{Plan}
					{Aux}
					{Diag_Diff}
					{Diag_Subst}
					<Diagnosis>
						{Diag_Type}
						{Diag_Sub_Type}
						{Diag_Div}
						{Diag_ID}
						{Diag_Tit}
						{Diag_FirstTime}
					</Diagnosis>
					{Recomm}
				</Epicrisis>
				<Drugs_Presc>
					{Date}
					{Series}
					{Number}
					{Drug_Tit}
					{Privilege}
					{Dos_Form}
					{Dose}
					{Quant}
					{Phys_ID}
					{Phys_Name}
					{Phys_Spec}
				</Drugs_Presc>
			</Visit>
			{/Visit}
			{Diagnosis}
			<Diagnosis>
				{Diag_Type}
				{Diag_Sub_Type}
				{Diag_Div}
				{Diag_ID}
				{Diag_Tit}
				{Diag_FirstTime}
			</Diagnosis>
			{/Diagnosis}
			{Disp_Obs_St}
			{Disp_Obs_Exp_Reas}
			{Trauma_Type}
			{Service}
			<Service>
				{Service_ID}
				{Service_Tit}
				{Service_Quant}
				{Phys_ID}
				{Phys_Name}
				{Phys_Spec}
			</Service>
			{/Service}
			{Sick_Leave_Pol}
			<Sick_Leave_Pol>
				{Type}
				{Reason}
				{Date_Beg}
				{Prol_Dates}
				{Date_End}
			</Sick_Leave_Pol>
			{/Sick_Leave_Pol}
			{TAP_Close_Date}
			{Phys_ID}
			{Phys_Name}
			{Phys_Spec}
			<Phys_Spec>
				{Phys_Spec_Tit}
				{Sert_Num}
				{Sert_Beg_Date}
				{Sert_Exp_Date}
			</Phys_Spec>
			{/Phys_Spec}
		</Medical_Record>
		{/Medical_Record}
		<Ins_Case_ID>
			{Rep_Per_ID}
			{MO_ID}
			{Ins_Comp_ID}
			{Pat_UID}
			{TAP_Num}
			{Med_Care_Prof}
			{Ins_Case_Date_Beg}
			{Ins_Case_Date_End}
			{Med_Care_Type}
			{Med_Care_Cond}
			{Diagnosis}
			<Diagnosis>
				{Diag_Type}
				{Diag_Sub_Type}
				{Diag_Div}
				{Diag_ID}
				{Diag_Tit}
				{Diag_FirstTime}
			</Diagnosis>
			{/Diagnosis}
			{Phys_ID}
			{Phys_Name}
		</Ins_Case_ID>
	</ZAP>
	{/ZAP}
</Root>
