		{ZAP_DATA}
		<ZAP>
			{N_ZAP}
			{ID_ZAP}
			{PR_NOV}

			{PACIENT_DATA}
			<PACIENT>
				{ID_PAC}
				{IND_CFOND}

				{OMS_DATA}
				<OMS>
					{VPOLIS}
					{SPOLIS}
					{NPOLIS}
					{SMO_OK}
					{SMO}
					{SMO_OGRN}
					{SMO_NAME}
				</OMS>
				{/OMS_DATA}

				{NOVOR}
				{INV}
				{VNOV_D}
				{C_OKSM}
				{KONT}
				{MSE}
				{COMENTP}
			</PACIENT>
			{/PACIENT_DATA}

			<SLUCH>
				{ID_CASE}
				{NUMBER}
				{NHISTORY}
				{DATE_1}
				{DATE_2}
				{PRVS}
				{ID_DOKT}
				{OS_SLUCH}
				{VNOV_M_DATA}
				{VNOV_M_VAL}
				{/VNOV_M_DATA}
				{REM_DATA}
				{REM_VAL}
				{/REM_DATA}
				{P_POST}
				{COMENTL}
				{TRAVMA}

				{DIR_IN_DATA}
				<DIR_IN>
					{ID_DIR}
					{NUM_DIR}
					{DATE_DIR}
					{EXTR}
					{NPR_MO}
					{R_NPR_MO}

					{NAPR_IN_DATA}
					<NAPR_IN>
						{NAPR_V}
						{MET_ISSL}
						{NAPR_USL}
					</NAPR_IN>
					{/NAPR_IN_DATA}
				</DIR_IN>
				{/DIR_IN_DATA}

				{SLUCH_MED_DATA}
				<SLUCH_MED>
					{ID_MED_USL}
					{ID_MED_TF}
					{USL_OK}
					{P_PER}
					{DATE_1_SM}
					{DATE_2_SM}
					{PRVS_SM}
					{CODE_MD}
					{VIDPOM}
					{FOR_POM}
					{LPU_1}
					{PODR}
					{PROFIL}
					{PROFIL_K}
					{DET}
					{DS0}
					{DS1}
					{DS2_DATA}
					{DS2}
					{/DS2_DATA}
					{DS3_DATA}
					{DS3}
					{/DS3_DATA}
					{C_ZAB}
					{REAB}
					{DS_ONK}
					{VNOV_M_SM_DATA}
					{VNOV_M_SM_VAL}
					{/VNOV_M_SM_DATA}
					{VIS_OB}
					{TYP_VIS}
					{CODE_USL_SM}
					{CODE_MES1}

					{CONS_DATA}
					<CONS>
						{PR_CONS}
						{DT_CONS}
					</CONS>
					{/CONS_DATA}

					{CODE_MES2}
					{GENERAL}
					{RSLT}
					{ISHOD}
					{IDSP}
					{ED_COL}
					{TARIF}
					{SUMV}
					{OPLATA}
					{SUMP}
					{SANK_IT}

					{HMP_DATA}
					<HMP>
						{VID_HMP}
						{METOD_HMP}
						{TAL_NUM}
						{TAL_D}
						{TAL_P}
					</HMP>
					{/HMP_DATA}

					{SANK_DATA}
					<SANK>
						{S_CODE}
						{S_SUM}
						{S_TIP}
						{EXPERT}
						{S_OSN}
						{S_IST}
						{COMENTSL}
					</SANK>
					{/SANK_DATA}

					{DIR_OUT_DATA}
					<DIR_OUT>
						{ID_DIR_DO}
						{NUM_DIR_DO}
						{DATE_DIR_DO}
						{EXTR_DO}
						{NPR_MO_DO}
						{R_NPR_MO_DO}
						{NAZ_SP_DO}
						{NAPR_OUT_DATA}
						<NAPR_OUT>
							{NAPR_V_DO}
							{MET_ISSL_DO}
							{NAPR_USL_DO}
						</NAPR_OUT>
						{/NAPR_OUT_DATA}
					</DIR_OUT>
					{/DIR_OUT_DATA}

					{USL_DATA}
					<USL>
						{ID_SERV}
						{ID_USL}
						{ID_MED_TF_USL}
						{LPU_1_USL}
						{PODR_USL}
						{PROFIL_USL}
						{DET_USL}
						{DATE_IN}
						{DATE_OUT}
						{DS}
						{DS_1}
						{CODE_USL}
						{KOL_USL}
						{NPL}
						{TARIF_USL}
						{SUMV_USL}
						{SUMP_USL}
						{PRVS_USL}
						{CODE_MD_USL}
						{COMENT_U}

						{SANK_USL_DATA}
						<SANK_USL>
							{S_CODE}
							{S_SUM}
							{S_SUMOD}
							{S_TIP}
							{EXPERT}
							{S_OSN}
							{S_COM}
							{S_IST}
							{COMENTSL}
						</SANK_USL>
						{/SANK_USL_DATA}
					</USL>
					{/USL_DATA}

					{LP_DATA}
					<LP>
						{ID_LP}
						{CODE_MD_LP}
						{NOMK_LS}
						{KO_ALL}
						{PRICE}
						{C_ZAK}
						{SUMV_LP}
						{COMENTLP}

						{LEK_PR_DATA}
						<LEK_PR>
							{REGNUM}
							{CODE_SH}
							{DATE_INJ_DATA}
							{DATE_INJ_VAL}
							{/DATE_INJ_DATA}
						</LEK_PR>
						{/LEK_PR_DATA}
					</LP>
					{/LP_DATA}

					{OPER_DATA}
					<OPER>
						{ID_OPER}
						{CODE_OPER}
						{NUMOPER}
						{FL_MAIN}
						{MKB_1}
						{MKB_2}
						{CODE_MD_OPER}
						{DATE_1_OPER}
						{DATE_2_OPER}
						{ID_TYPE}
						{N_HOUR}
						{KIF}
						{ID_AN}
						{FL_DIE}
						{PR_FIRST}
						{ID_AB}
						{P_AB}
						{COMENTO}
					</OPER>
					{/OPER_DATA}

					{KOEF_DATA}
					<KOEF>
						{N_KSG}
						{VER_KSG}
						{BS}
						{KZ}
						{KUS}
						{KD}
						{UK}
						{CRIT_DATA}
						{CRIT_VAL}
						{/CRIT_DATA}
						{KPL}
						{KSDL}
						{SL_K}
						{IT_SL}

						{SL_KOEF_DATA}
						<SL_KOEF>
							{IDSL}
							{Z_SL}
						</SL_KOEF>
						{/SL_KOEF_DATA}
					</KOEF>
					{/KOEF_DATA}

					{DOP_K_DATA}
					<DOP_K>
						{SLT}
						{SRM}
						{INDBAR}
						{SOFA}
					</DOP_K>
					{/DOP_K_DATA}

					{ONK_SL_DATA}
					<ONK_SL>
						{DS1_T}
						{STAD}
						{ONK_T}
						{ONK_N}
						{ONK_M}
						{MTSTZ}
						{SOD}
						{K_FR}
						{WEI}
						{HEI}
						{BSA}

						{B_DIAG_DATA}
						<B_DIAG>
							{DIAG_DATE}
							{DIAG_TIP}
							{DIAG_CODE}
							{DIAG_RSLT}
							{REC_RSLT}
						</B_DIAG>
						{/B_DIAG_DATA}

						{B_PROT_DATA}
						<B_PROT>
							{PROT}
							{D_PROT}
						</B_PROT>
						{/B_PROT_DATA}

						{ONK_USL_DATA}
						<ONK_USL>
							{USL_TIP}
							{HIR_TIP}
							{LEK_TIP_L}
							{LEK_TIP_V}
							{PPTR}
							{LUCH_TIP}
						</ONK_USL>
						{/ONK_USL_DATA}
					</ONK_SL>
					{/ONK_SL_DATA}

					{PAIN_DATA}
					<PAIN>
						{IDPAINLVL}
						{DS_R52}
					</PAIN>
					{/PAIN_DATA}

					{DISPN_DATA}
					<DISPN>
						{MKB}
						{DATE_MKB}
						{FIRST}
						{GROUP_DN}
						{DISPD}
						{DISPD_END}
						{DN}
						{DATE_NEXT}
					</DISPN>
					{/DISPN_DATA}

					{COMENTSM}
				</SLUCH_MED>
				{/SLUCH_MED_DATA}
			</SLUCH>
			{NO_EKMP}
		</ZAP>
		{/ZAP_DATA}
