<Root>
	<Header>
		{Version}
		{Date}
	</Header>
	{ZAP}
	<ZAP>
		{N_ZAP}
		{Patient}
		<Patient>
			{Blood_Type}
			{Rh_Type}
			{Last_Name}
			{First_Name}
			{Midd_Name}
			{Age}
			{Perm_Addr}
			{Area_Type}
			{Work_Loc}
			{Deliv_MO}
			{Deliv_Ext}
			{Work_Abil}
			{Inf_Consent_Data}
			{Inf_Cons_Med_Int}
			{Refusal}
			{Anest_Cons}
		</Patient>
		{/Patient}
        {Medical_Record}
		<Medical_Record>
			{Med_Card_Num}
			{SKVS_Num}
			{Deliv}
			{Amb_Ord_ID}
			{Diagnosis}
			<Diagnosis>
				{Diag_Type}
				{Diag_Sub_Type}
				{Diag_Div}
				{Diag_ID}
				{Diag_Tit}
			</Diagnosis>
			{/Diagnosis}
			{Intox}
			{Dis_Mult_Year}
			{Dis_Time_Beg}
			{Trauma}
			{Recp_Date}
			{Dep_Tit}
			{Dep_Date}
			{PhysID}
			{Phys_Name}
			{Phys_Spec}
			<Phys_Spec>
				{Phys_Spec_Tit}
				{Sert_Num}
				{Sert_Beg_Date}
				{Sert_Exp_Date}
			</Phys_Spec>
			{/Phys_Spec}
			{Disch_Date}
			{Duration}
			<Sick_Leave_Pol>
				{Date_Open}
				{Date_Close}
				{Pat_Care}
				{Age}
				{Sex}
			</Sick_Leave_Pol>
			{Depart_Mov}
			<Depart_Mov>
				{Depart_ID}
				{Depart_Tit}
				{Depart_Prof_ID}
				{Phys_ID}
				{Phys_Name}
                {Phys_Spec}
				<Phys_Spec>
					{Phys_Spec_Tit}
					{Sert_Num}
					{Sert_Beg_Date}
					{Sert_Exp_Date}
				</Phys_Spec>
                {/Phys_Spec}
				{Recp_Date}
				{Disch_Date}
				{Duration}
				{Res_Per}
                {Diagnosis}
				<Diagnosis>
					{Diag_Type}
					{Diag_Sub_Type}
					{Diag_Div}
					{Diag_ID}
					{Diag_Tit}
				</Diagnosis>
                {/Diagnosis}
			</Depart_Mov>
			{/Depart_Mov}
			{Surgery}
			<Surgery>
				{Surg_Date}
				{Phys_ID}
				{Phys_Name}
				<Phys_Spec>
					{Phys_Spec_Tit}
					{Sert_Num}
					{Sert_Beg_Date}
					{Sert_Exp_Date}
				</Phys_Spec>
				{Depart_ID}
				{Depart_Tit}
				{Oper_ID}
				{Oper_Tit}
				{Oper_Comp}
				{Anesthesia}
				{Equipment}
			</Surgery>
			{/Surgery}
			{Recp_Serv}
			<Recp_Serv>
				{Serv_ID}
				{Serv_Tit}
				{Serv_Date}
				{Phys_ID}
				{Phys_Name}
				{Phys_Spec}
			</Recp_Serv>
			{/Recp_Serv}
			{Anamnesis}
			<Anamnesis>
				{Type}
				{Record}
			</Anamnesis>
			{/Anamnesis}
			{Phys_Rec}
			<Phys_Rec>
				{Rec_Date}
				{Compl}
				{Anamnesis}
				<Anamnesis>
					{Type}
					{Record}
				</Anamnesis>
				{/Anamnesis}
				{Obj_Stat}
				{Loc_Stat}
				{CaseMonitoring}
				{Protocol}
				{Appointment}
				{Prescription}
				{Conclusion}
				{Recomm}
				{Plan}
				{Treatment}
				{Aux}
				{Diag_Diff}
				{Diag_Subst}
				<Diagnosis>
					{Diag_Type}
					{Diag_Sub_Type}
					{Diag_Div}
					{Diag_ID}
					{Diag_Tit}
				</Diagnosis>
			</Phys_Rec>
			{/Phys_Rec}
			{Epicrisis}
			<Epicrisis>
				{Date}
				{Type}
				{Compl}
				{Anamnesis}
				<Anamnesis>
					{Type}
					{Record}
				</Anamnesis>
				{/Anamnesis}
				{Dyn_Obj_Stat}
				{Dyn_Loc_Stat}
				{Epicrisis}
				{Treat}
				{Plan}
				{Aux}
				{Diag_Diff}
				{Diag_Subst}
				<Diagnosis>
					{Diag_Type}
					{Diag_Sub_Type}
					{Diag_Div}
					{Diag_ID}
					{Diag_Tit}
				</Diagnosis>
				{Recomm}
			</Epicrisis>
			{/Epicrisis}
			{Drugs_Presc}
			<Drugs_Presc>
				{MO_ID}
				{Phys_ID}
				{Phys_Name}
				{Phys_Spec}
				{Drug_Tit}
				{Dos_Form}
				{Dose}
				{App_Dose_Quant}
				{Freq}
				{Drug_Taking}
				{Date}
				{Medic_Beg}
				{Medic_End}
			</Drugs_Presc>
			{/Drugs_Presc}
			{RW}
			{AIDS}
		</Medical_Record>
        {/Medical_Record}
        {Ins_Case_ID}
		<Ins_Case_ID>
			{Rep_Per_ID}
			{MO_ID}
			{Ins_Comp_ID}
			{Pat_UID}
			{Med_Card_Num}
			{Ins_Case_Date_Beg}
			{Ins_Case_Date_End}
			{Med_Care_Type}
			{Med_Care_Cond}
		</Ins_Case_ID>
        {/Ins_Case_ID}
	</ZAP>
	{/ZAP}
</Root>