{ZAP}
<ZAP>
    <N_ZAP>{N_ZAP}</N_ZAP>
    <PR_NOV>{PR_NOV}</PR_NOV>
    {PACIENT}
    <PACIENT>
        {ID_PAC}
        {VPOLIS}
        {SPOLIS}
        {NPOLIS}
        {SMO}
        {SMO_OK}
        {NOVOR}
        {VNOV_D}
        {SOC_ST}
        {INV}
        {MSE}
    </PACIENT>
    {/PACIENT}
    {SLUCH}
    <SLUCH>
        {IDCASE}
        {USL_OK}
        {VIDPOM}
        {VID_HMP}
        {METOD_HMP}
        {TIP_DISP}
        {NPR_MO}
        {NPR_DOCTOR}
        {NPR_TYPE}
        {NPR_NUM}
        {NPR_DATE}
        {EXTR}
        {DS_ONK}
        {DS_ONKNOT}
        {DATE_BP}

        {NAPR_DATA}
        <NAPR>
            {NAPR_DATE}
            {NAPR_MO}
            {NAPR_V}
            {MET_ISSL}
            {NAPR_USL}
        </NAPR>
        {/NAPR_DATA}

		{CONS_DATA}
		<CONS>
			{PR_CONS}
			{DT_CONS}
			{LECH_TIP}
			{LECH_SHEM}
			{LECH_DATE}
		</CONS>
		{/CONS_DATA}

        {ONK_SL_DATA}
        <ONK_SL>
            {DS1_T}
            {STAD}
            {ONK_T}
            {ONK_N}
            {ONK_M}
            {MTSTZ}

            {B_DIAG_DATA}
            <B_DIAG>
                {DIAG_DATE}
                {DIAG_TIP}
                {DIAG_CODE}
                {DIAG_RSLT}
                {REC_RSLT}
            </B_DIAG>
            {/B_DIAG_DATA}

            {B_PROT_DATA}
            <B_PROT>
                {PROT}
                {D_PROT}
            </B_PROT>
            {/B_PROT_DATA}

            {ONK_USL_DATA}
            <ONK_USL>
                {IDSERV_ONK}
                {USL_TIP}
                {HIR_TIP}
                {LEK_TIP_L}
                {LEK_TIP_V}
                {LEK_SHEM}
				{LEK_PR_DATA}
				<LEK_PR>
					{REGNUM}
					{DATE_INJ_DATA}
					{DATE_INJ}
					{/DATE_INJ_DATA}
				</LEK_PR>
				{/LEK_PR_DATA}
                {PPTR}
                {LUCH_TIP}
                {LUCH_SNS}
                {SOD}
                {WEI}
                {HEI}
                {BSA}
            </ONK_USL>
            {/ONK_USL_DATA}
        </ONK_SL>
        {/ONK_SL_DATA}
        {LPU_1}
        {VBR}
        {PODR}
        {PROFIL}
        {TAL_NUM}
        {TAL_D}
        {TAL_P}
        {NHISTORY}
        {P_PER}
        {DATE_1}
        {DATE_2}
        {KD}
        {PREGTIME}
        {C_ZAB}
        {DS1}
        {DS1_PR}

        {DS2_DATA}
        <DS2_N>
            {DS2}{DS2_PR}
        </DS2_N>
        {/DS2_DATA}

        {CODE_MES1}
        {CODE_MES2}
        {RSLT}
        {RSLT_D}

        {NAZ}
        <NAZ>
            {NAZR_N}
            {NAZR}
            {NAZ_SP}
            {NAZ_V}
            {NAZ_PMP}
            {NAZ_PK}
        </NAZ>
        {/NAZ}

        {ISHOD}
        {PRVS}
        {IDDOKT}

        {OS_SLUCH}
        <OS_SLUCH>{OS_SLUCH_VAL}</OS_SLUCH>
        {/OS_SLUCH}

        {IDSP}
        {FOR_POM}

        {DS3_DATA}
        {DS3}
        {/DS3_DATA}

        {DS0}
        {DISP}
        {TRAVMA}
        {GRZD}
        {VNOV_M}
        {RANKIN_IN}
        {RANKIN_OUT}
        {COMENTSL}

        {USL}
        <USL>
            {IDSERV}
            {LPU_USL}
            {LPU_1_USL}
            {PODR_USL}
            {PROFIL_USL}
            {PROFIL_K_USL}
            {P_CEL_USL}
            {DATE_IN_USL}
            {DATE_OUT_USL}
            {TIME_IN}
            {TIME_OUT}
            {DS_USL}
            {RAZDEL_USL}
            {CODE_USL}
            {KOL_USL}
            {PRVS_USL}
            {CODE_MD_USL}
            {NPR_DC_USL}
            {DST_MO}
            {NPL}
            {UP_ST}
            {DENTAL}
            {DENTAL_KPU}
            {DENTAL_KOL}
            {DENTAL_SIDE}
            {CLASS_BLACK}
            {COMENTU}
        </USL>
        {/USL}
    </SLUCH>
    {/SLUCH}
</ZAP>
{/ZAP}
