{ZAP}
<ZAP>
    <N_ZAP>{N_ZAP}</N_ZAP>
    <PR_NOV>{PR_NOV}</PR_NOV>
    <PACIENT>
        {ID_PAC}
        {SMO}
    </PACIENT>
    {SLUCH}
    <SLUCH>
        <IDCASE>{IDCASE}</IDCASE>
        {USL_OK}
        {VIDPOM}
        {FOR_POM}
        {NPR_MO}
        {EXTR}
        {VID_HMP}
        {METOD_HMP}
        {LPU}
        {LPU_1}
        {PODR}
        {PROFIL}
        {DET}
        {NHISTORY}
        {DATE_1}
        {DATE_2}
        {DS0}
        {DS1}
        {DS2}
        {CODE_MES1}
        {CODE_MES2}
        {RSLT}
        {ISHOD}
        {PRVS}
        {VERS_SPEC}
        {IDDOKT}
        {OS_SLUCH}
        <OS_SLUCH>{OS_SLUCH_VAL}</OS_SLUCH>
        {/OS_SLUCH}
        {IDSP}
        {ED_COL}
        {TARIF}
        {SUMV}
        {OPLATA}

        {VPRINAD}
        {DATE_OPL}
        {SUMV_OPL}
        {SUMP}
        {REFREASON}
        {SANK_MEK}
        {SANK_MEE}
        {SANK_EKMP}

        {USL}
        <USL>
            {IDSERV}
            {USL_LPU}
            {USL_LPU_1}
            {USL_PODR}
            {USL_PROFIL}
            {USL_DET}
            {DATE_IN}
            {DATE_OUT}
            {DS}
            {CODE_USL}
            {KOL_USL}
            {TARIF_USL}
            {SUMV_USL}
            {USL_PRVS}
            {CODE_MD}
            {COMENTU}
        </USL>
        {/USL}
        {COMENTSL}
    </SLUCH>
    {/SLUCH}
</ZAP>
{/ZAP}
