		{ZAP_DATA}
		<ZAP>
			{N_ZAP}
			{ID_ZAP}
			{PR_NOV}

			{PACIENT_DATA}
			<PACIENT>
				{ID_PAC}
				{DISP}
				{IND_CFOND}

				{OMS_DATA}
				<OMS>
					{VPOLIS}
					{SPOLIS}
					{NPOLIS}
					{SMO_OK}
					{SMO}
					{SMO_OGRN}
					{SMO_NAME}
				</OMS>
				{/OMS_DATA}

				{NOVOR}
				{AGE_GR}
				{KONT}
				{C_KAT}
				{NORD}
				{COMENTP}
			</PACIENT>
			{/PACIENT_DATA}

			<SLUCH>
				{ID_CASE}
				{NUM_LAP}
				{VIS_OBN}
				{VIDPOM_SLUCH}
				{LPU_1}
				{NUMBER}
				{NHISTORY}
				{DATE_1}
				{DATE_2}

				{DS1_DATA}
				<DS1>
					{MKB}
					{FIRST}
					{DISPD}
					{PR_D_N}
					{GROUP_DN}
					{DISPD_END}
					{DATE_NEXT}
				</DS1>
				{/DS1_DATA}

				{RSLT_D}
				{FIZ_GR}
				{VBR}
				{RES_G}
				{NEED}
				{PR_OTK_SLUCH}
				{L_LS}

				{DIR_TO_DATA}
				{DIR_TO_VAL}
				{/DIR_TO_DATA}

				{O_SC}
				{A_SC}
				{IDSP}
				{TARIF_SLUCH}
				{SUMV}
				{OPLATA}
				{SUMP}
				{SANK_IT}

				{NAZR_DATA}
				<NAZR>
					{NAZ}
					{NAZ_SP}
					{NAZ_V}
					{NAZ_USL}
					{NAPR_DATE}
					{NAPR_MO}
					{NAZ_PMP}
					{NAZ_PK}
				</NAZR>
				{/NAZR_DATA}

				{SANK_DATA}
				<SANK>
					{S_CODE}
					{S_SUM}
					{S_TIP}
					{S_OSN}
					{S_IST}
					{COMENTSL}
					{EXPERT}
				</SANK>
				{/SANK_DATA}

				{OSM_DATA}
				<OSM>
					{ID_OL_OSM}
					{PRVS_OSM}
					{VIDPOM_OSM}
					{CODE_USL_OSM}
					{PCOD_OSM}
					{SS_V_OSM}
					{DLOOK_OSM}

					{SDIAG_DATA}
					<SDIAG>
						{LMKB_OSM}
						{L_FIRST_OSM}
						{L_LAST_OSM}
						{L_MAIN_OSM}
						{L_PREDV_OSM}
						{DS_ONK_OSM}
					</SDIAG>
					{/SDIAG_DATA}

					{L_GROUP_OSM}
					{TARIF_OSM}
					{SL_ALL_OSM}
					{SP_ALL_OSM}
					{REF_OSM}
					{PR_OTK_OSM}
					{IDMU_OSM}
					{MU_NAME_OSM}
					{TYP_VIS_OSM}
					{COMENTOSM_OSM}
					{SANK_OSM_DATA}
					<SANK_OSM>
						{S_CODE}
						{S_SUM}
						{S_TIP}
						{S_OSN}
						{S_IST}
						{COMENTSL}
						{EXPERT}
					</SANK_OSM>
					{/SANK_OSM_DATA}
				</OSM>
				{/OSM_DATA}

				{OBSL_DATA}
				<OBSL>
					{ID_ANAL_OBSL}
					{IDANALYS_OBSL}
					{LABBEGIN_OBSL}
					{TARIF_OBSL}
					{SL_ALL_OBSL}
					{SP_ALL_OBSL}
					{PRVS_OBSL}
					{CODE_MD_OBSL}
					{REF_OBSL}
					{PR_OTK_OBSL}
					{IDMU_OBSL}
					{MU_NAME_OBSL}
					{VAR_OBSL}
					{TYP_VIS_OBSL}
					{COMENTOBS_OBSL}
					{SANK_OBS_DATA}
					<SANK_OBS>
						{S_CODE}
						{S_SUM}
						{S_TIP}
						{S_OSN}
						{S_IST}
						{COMENTSL}
						{EXPERT}
					</SANK_OBS>
					{/SANK_OBS_DATA}
					{USL_LAB_DATA}
					<USL_LAB>
						{COD_LAB}
						{LAB_VALUE}
						{LAB_UNIT}
						{LAB_RSL}
					</USL_LAB>
					{/USL_LAB_DATA}
					{USL_DIAG_DATA}
					<USL_DIAG>
						{PATF}
						{COD_PATF_DATA}
						{COD_PATF_VAL}
						{/COD_PATF_DATA}
					</USL_DIAG>>
					{/USL_DIAG_DATA}
				</OBSL>
				{/OBSL_DATA}

				{RISK_DATA}
				<RISK>
					{DSFAKTOR}
					{COMENTR}
				</RISK>
				{/RISK_DATA}

				{PR_PAT}
				{COMENTL}
			</SLUCH>
			{NO_EKMP}
		</ZAP>
		{/ZAP_DATA}
