	{ZAP}
	<ZAP>
		<N_ZAP>{N_ZAP}</N_ZAP>
		<PR_NOV>{PR_NOV}</PR_NOV>
		{PACIENT}
		<PACIENT>
			{ID_PAC}
			{VPOLIS}
			{SPOLIS}
			{NPOLIS}
			{ST_OKATO}
			{SMO}
			{SMO_OGRN}
			{SMO_OK}
			{SMO_NAM}
		</PACIENT>
		{/PACIENT}
		{SLUCH}
		<SLUCH>
			<IDCASE>{IDCASE}</IDCASE>
			{USL_OK}
			{VIDPOM}
			{FOR_POM}
			{LPU}
			{LPU_1}
			{VBR}
			{NHISTORY}
			{P_OTK}
			{DATE_1}
			{DATE_2}
			{DS1}
			{DS1_PR}
			{CODE_MES1}
			{RSLT_D}
			{ISHOD}
			{CEL_OBR}
			{NAZR_DATA}<NAZR>{NAZR}</NAZR>{/NAZR_DATA}
			{NAZ_SP_DATA}<NAZ_SP>{NAZ_SP}</NAZ_SP>{/NAZ_SP_DATA}
			{NAZ_V_DATA}<NAZ_V>{NAZ_V}</NAZ_V>{/NAZ_V_DATA}
			{NAZ_PMP}
			{NAZ_PK}
			{PR_D_N}
			{PRVS}
			{IDDOKT}
			{IDSP}
			{ED_COL}
			{TARIF}
			{SUMV}
			{OPLATA}
			{SUMP}
			{COMENTSL}
			{DS2_DATA}
			<DS2_N>
				{DS2}
				{DS2_PR}
			</DS2_N>
			{/DS2_DATA}
			{USL}
			<USL>
				{IDSERV}
				{LPU_USL}
				{LPU_1_USL}
				{DATE_IN}
				{DATE_OUT}
				{P_OTK_USL}
				{CODE_USL}
				{KOL_USL}
				{TARIF_USL}
				{SUMV_USL}
				{PRVS_USL}
				{CODE_MD}
				{COMENTU}
			</USL>
			{/USL}
		</SLUCH>
		{/SLUCH}
	</ZAP>
	{/ZAP}