    <row>
        <surname>{surname}</surname>
        <birth_name>{surname}</birth_name>
        <name>{name}</name>
        <patroname>{patroname}</patroname>
        <sex>{sex}</sex>
        <birthdate>{birthdate}</birthdate>
        <ser_pol_oms>{ser_pol_oms}</ser_pol_oms>
        <sernum_pol_oms>{sernum_pol_oms}</sernum_pol_oms>
        <ins_company>{ins_company}</ins_company>
        <terr_code>{terr_code}</terr_code>
        <address>{address}</address>
        <okato>{okato}</okato>
        <id_docum_type>{id_docum_type}</id_docum_type>
        <ser_docum>{ser_docum}</ser_docum>
        <num_docum>{num_docum}</num_docum>
        <issue_docum>{issue_docum}</issue_docum>
        <when_docum>{when_docum}</when_docum>
        <id_mkb>{id_mkb}</id_mkb>
        <inst_code>{inst_code}</inst_code>
        <change_date_out>{change_date_out}</change_date_out>
        <inst_name_out>{inst_name_out}</inst_name_out>
        <inst_code_out>{inst_code_out}</inst_code_out>
        <physically_challenged>{physically_challenged}</physically_challenged>
        <death_date>{death_date}</death_date>
        <therapy_resistance>{therapy_resistance}</therapy_resistance>
        <dis_register_1>{dis_register_1}</dis_register_1>
        <ins_account_num>{ins_account_num}</ins_account_num>
        <dis_register_2>{dis_register_2}</dis_register_2>
        <dis_signed>{dis_signed}</dis_signed>
        <u_numb_regist_record>{u_numb_regist_record}</u_numb_regist_record>
        <operation_code_id>{operation_code_id}</operation_code_id>
        <organ_ispoln_vlast_sf>{organ_ispoln_vlast_sf}</organ_ispoln_vlast_sf>
        <head_person>{head_person}</head_person>
        <change_datetime>{change_datetime}</change_datetime>
        <fcomment>{fcomment}</fcomment>
        <inst_name>{inst_name}</inst_name>
    </row>