    <row>
        <u_numb_regist_record_04>{u_numb_regist_record_04}</u_numb_regist_record_04>
        <u_numb_regist_record>{u_numb_regist_record}</u_numb_regist_record>
        <gos_numb_okop_uz>{gos_numb_okop_uz}</gos_numb_okop_uz>
        <pres_doctor>{pres_doctor}</pres_doctor>
        <pres_ser_num>{pres_ser_num}</pres_ser_num>
        <pres_date>{pres_date}</pres_date>
        <okato>{okato}</okato>
        <prepar_name>{prepar_name}</prepar_name>
        <doza_count>{doza_count}</doza_count>
        <terr_code>{terr_code}</terr_code>
        <pharmacy_reg_no>{pharmacy_reg_no}</pharmacy_reg_no>
        <pharmacy_date_out1>{pharmacy_date_out1}</pharmacy_date_out1>
        <lekarstv_name>{lekarstv_name}</lekarstv_name>
        <mkb_code>{mkb_code}</mkb_code>
        <lekarstv_forma>{lekarstv_forma}</lekarstv_forma>
        <lekarstv_doza_pres>{lekarstv_doza_pres}</lekarstv_doza_pres>
        <lekarstv_doza_pack>{lekarstv_doza_pack}</lekarstv_doza_pack>
        <lekarstv_packs_out>{lekarstv_packs_out}</lekarstv_packs_out>
        <operation_code>{operation_code}</operation_code>
        <head_person>{head_person}</head_person>
        <organ_ispoln_vlast_sf>{organ_ispoln_vlast_sf}</organ_ispoln_vlast_sf>
        <id_istochnik_finans>{id_istochnik_finans}</id_istochnik_finans>
        <fcomment>{fcomment}</fcomment>
    </row>