Ext6.define('usluga.oper.models.UslugaOperFormModel', {
	extend: 'Ext6.data.Model',
	alias: 'model.UslugaOperFormModel',
	idProperty: 'EvnUslugaOper_id',
	fields: [
		{name: 'accessType'},
		{name: 'XmlTemplate_id'},
		{name: 'EvnUslugaOper_id'},
		{name: 'EvnUslugaOper_CoeffTariff'},
		{name: 'EvnUslugaOper_IsEndoskop'},
		{name: 'EvnUslugaOper_IsKriogen'},
		{name: 'EvnUslugaOper_IsLazer'},
		{name: 'EvnUslugaOper_IsRadGraf'},
		{name: 'EvnUslugaOper_IsModern'},
		{name: 'EvnUslugaOper_Kolvo'},
		{name: 'EvnUslugaOper_pid'},
		{name: 'EvnDirection_id'},
		{name: 'EvnUslugaOper_Price'},
		{name: 'EvnUslugaOper_rid'},
		{name: 'EvnUslugaOper_setDate', type: 'date', dateFormat: 'd.m.Y'},
		{name: 'EvnUslugaOper_setTime'},
		{name: 'EvnUslugaOper_disDate', type: 'date', dateFormat: 'd.m.Y'},
		{name: 'EvnUslugaOper_disTime'},
		{name: 'Lpu_uid'},
		{name: 'LpuSection_uid'},
		{name: 'MedStaffFact_id'},
		{name: 'MesOperType_id'},
		{name: 'Morbus_id'},
		{name: 'Org_uid'},
		{name: 'OperDiff_id'},
		{name: 'TreatmentConditionsType_id'},
		{name: 'EvnUslugaOper_IsVMT'},
		{name: 'EvnUslugaOper_IsMicrSurg'},
		{name: 'EvnUslugaOper_IsOpenHeart'},
		{name: 'EvnUslugaOper_IsArtCirc'},
		{name: 'OperType_id'},
		{name: 'PayType_id'},
		{name: 'Person_id'},
		{name: 'PersonEvn_id'},
		{name: 'Server_id'},
		{name: 'UslugaComplex_id'},
		{name: 'UslugaComplexTariff_id'},
		{name: 'DiagSetClass_id'},
		{name: 'Diag_id'},
		{name: 'EvnPrescr_id'},
		{name: 'LpuSectionProfile_id'},
		{name: 'MedSpecOms_id'},
		{name: 'EvnUslugaCommon_pid_Name'},
		{name: 'UslugaPlace_id'},
		{name: 'EvnUslugaOper_BallonBegDate', type: 'date', dateFormat: 'd.m.Y' },
		{name: 'EvnUslugaOper_BallonBegTime'},
		{name: 'EvnUslugaOper_CKVEndDate', type: 'date', dateFormat: 'd.m.Y'},
		{name: 'EvnUslugaOper_CKVEndTime'},
		{name: 'EvnUslugaOper_IsOperationDeath'},
		{name: 'UslugaExecutionType_id'},
		{name: 'UslugaExecutionReason_id'}
	]
});