<?php
$is_allow_edit=true;?>
<div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}" class="specifics">
<div class="data-row-container" style="display:none"><div class="data-row">Заполнить данные по беременности: <span<?php if ($is_allow_edit) { ?> id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputTrueStream" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregnancy_TrueStream}'><?php echo empty($MorbusPregnancy_TrueStream) ? 'Нет' : '{MorbusPregnancy_TrueStreamName}'; ?></span></div><div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputareaTrueStream" class="input-area"></div></div>
<div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_block"  >
<div class="data-row-container"><div class="data-row">Которая беременность: <span<?php if ($is_allow_edit) { ?> id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputCountPreg" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregnancy_CountPreg) ? "Пусто" : '{MorbusPregnancy_CountPreg}'; ?></span></div><div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputareaCountPreg" class="input-area"></div></div>
<div class="data-row-container"><div class="data-row">Дата исхода беременности: <span<?php if ($is_allow_edit) { ?> id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputOutcomD" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregnancy_OutcomD) ? "Пусто" : '{MorbusPregnancy_OutcomD}'; ?></span></div><div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputareaOutcomD" class="input-area"></div></div>
<div class="data-row-container"><div class="data-row">Время: <span<?php if ($is_allow_edit) { ?> id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputOutcomT" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregnancy_OutcomT) ? "Пусто" : '{MorbusPregnancy_OutcomT}'; ?></span></div><div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputareaOutcomT" class="input-area"></div></div>
<div class="data-row-container"><div class="data-row">Исход беременности: <span<?php if ($is_allow_edit) { ?> id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputBirthResult" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{BirthResult_id}'><?php echo empty($BirthResult_id_Name) ? 'Пусто' : '{BirthResult_id_Name}'; ?></span></div><div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputareaBirthResult" class="input-area"></div></div>
<div class="data-row-container"><div class="data-row">Срок, недель: <span<?php if ($is_allow_edit) { ?> id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputOutcomPeriod" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregnancy_OutcomPeriod) ? "Пусто" : '{MorbusPregnancy_OutcomPeriod}'; ?></span></div><div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputareaOutcomPeriod" class="input-area"></div></div>

<div class="data-row-container"><div class="data-row">Тип Аборта: <span<?php if ($is_allow_edit) { ?> id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputAbortType_id" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{AbortType_id}'><?php echo empty($AbortType_id_Name) ? 'Пусто' : '{AbortType_id_Name}'; ?></span></div><div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputareaAbortType_id" class="input-area"></div></div>

<div class="data-row-container"><div class="data-row">Медикаментозный: <span<?php if ($is_allow_edit) { ?> id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputIsMedicalAbort" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregnancy_IsMedicalAbort}'><?php echo empty($MorbusPregnancy_IsMedicalAbort) ? 'Пусто' : '{MorbusPregnancy_IsMedicalAbortName}'; ?></span></div><div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputareaIsMedicalAbort" class="input-area"></div></div>
<div class="data-row-container"><div class="data-row">Кровопотери (мл) <span<?php if ($is_allow_edit) { ?> id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputBloodLoss" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregnancy_BloodLoss) ? "Пусто" : '{MorbusPregnancy_BloodLoss}'; ?></span></div><div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputareaBloodLoss" class="input-area"></div></div>
<div class="data-row-container"><div class="data-row">Обследована на ВИЧ: <span<?php if ($is_allow_edit) { ?> id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputIsHIVtest" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregnancy_IsHIVtest}'><?php echo empty($MorbusPregnancy_IsHIVtest) ? 'Пусто' : '{MorbusPregnancy_IsHIVtestName}'; ?></span></div><div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputareaIsHIVtest" class="input-area"></div></div>
<div class="data-row-container"><div class="data-row">Наличие ВИЧ-инфекции: <span<?php if ($is_allow_edit) { ?> id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputIsHIV" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregnancy_IsHIV}'><?php echo empty($MorbusPregnancy_IsHIV) ? 'Пусто' : '{MorbusPregnancy_IsHIVName}'; ?></span></div><div id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_inputareaIsHIV" class="input-area"></div></div>
<a id="MorbusPregnancy_{MorbusPregnancy_pid}_{MorbusPregnancy_id}_save" style="float: right;" class="button icon icon-save16" title="Сохранить"><span></span></a>
</div>
</div>

