<?php
	$empty_str = '<span style="color: #666;">Не указано</span>';
	$is_allow_edit = ('edit' == $accessType);

?>
<div class="left">
	<div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}"
		 data-armType="<?php echo (!empty($_SESSION['CurArmType']) ? $_SESSION['CurArmType'] : '' );  ?>"
		 data-talonStatus="<?php echo (!empty($ElectronicTalonStatus_id) ? $ElectronicTalonStatus_id : '' );  ?>"
		 data-osmotrService="<?php echo (!empty($ElectronicService_id) ? $ElectronicService_id : '' );  ?>"
		 data-curService="<?php echo ((!empty($_SESSION['CurARM']) && !empty($_SESSION['CurARM']['ElectronicService_id'])) ? $_SESSION['CurARM']['ElectronicService_id'] : '' );  ?>"
		 data-eqOff="<?php echo (!empty($ElectronicQueueInfo_IsOff) ? $ElectronicQueueInfo_IsOff : '' );  ?>"
	>
		<div class="caption">
			<h2>{DispClass_Name}
			</h2>
		</div>
		<div class="text">
			<p>Автор документа: {AuthorInfo}</p>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Вид оплаты: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputPayType" style='color:#000;' class="link" dataid='{PayType_id}'><?php } echo empty($PayType_Name)?$empty_str:'{PayType_Name}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaPayType" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Дата начала медицинского осмотра: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputSetDate" style='color:#000;' class="link" dataid='{EvnPLDispTeenInspection_setDate}'><?php } echo empty($EvnPLDispTeenInspection_setDate)?$empty_str:'{EvnPLDispTeenInspection_setDate}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaSetDate" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Возрастная группа: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputAgeGroupDisp" style='color:#000;' class="link" dataid='{AgeGroupDisp_id}'><?php } echo empty($AgeGroupDisp_Name)?$empty_str:'{AgeGroupDisp_Name}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaAgeGroupDisp" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<!-- Информированное добровольное согласие -->
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Дата подписания согласия/отказа: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputConsDate" style='color:#000;' class="link" dataid='{EvnPLDispTeenInspection_consDate}'><?php } echo empty($EvnPLDispTeenInspection_consDate)?$empty_str:'{EvnPLDispTeenInspection_consDate}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaConsDate" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			{DopDispInfoConsent}
			<!-- Маршрутная карта -->
			{EvnUslugaDispDop}
			<!-- Диагнозы и рекомендации -->
			{EvnDiagAndRecomendation}
			<!-- Состояние здоровья до проведения диспансеризации / профосмотра -->
			{EvnDiagDopDispAndRecomendation}
			<!-- Общая оценка здоровья -->
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Дата поступления: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputEduDate" style='color:#000;' class="link" dataid='{EvnPLDispTeenInspection_eduDate}'><?php } echo empty($EvnPLDispTeenInspection_eduDate)?$empty_str:'{EvnPLDispTeenInspection_eduDate}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaEduDate" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Образовательное учреждение: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputEducationInstitutionClass" style='color:#000;' class="link" dataid='{EducationInstitutionClass_id}'><?php } echo empty($EducationInstitutionClass_Name)?$empty_str:'{EducationInstitutionClass_Name}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaEducationInstitutionClass" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Характер учреждения: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputInstitutionNatureType" style='color:#000;' class="link" dataid='{InstitutionNatureType_id}'><?php } echo empty($InstitutionNatureType_Name)?$empty_str:'{InstitutionNatureType_Name}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaInstitutionNatureType" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Вид учреждения: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputInstitutionType" style='color:#000;' class="link" dataid='{InstitutionType_id}'><?php } echo empty($InstitutionType_Name)?$empty_str:'{InstitutionType_Name}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaInstitutionType" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Масса (кг): <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputWeight" style='color:#000;' class="link" dataid='{AssessmentHealth_Weight}'><?php } echo empty($AssessmentHealth_Weight)?$empty_str:'{AssessmentHealth_Weight}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaWeight" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Рост (см): <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputHeight" style='color:#000;' class="link" dataid='{AssessmentHealth_Height}'><?php } echo empty($AssessmentHealth_Height)?$empty_str:'{AssessmentHealth_Height}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaHeight" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Тип отклонения (масса): <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputWeightAbnormType" style='color:#000;' class="link" dataid='{WeightAbnormType_id}'><?php } echo empty($WeightAbnormType_Name)?$empty_str:'{WeightAbnormType_Name}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaWeightAbnormType" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Тип отклонения (рост): <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputHeightAbnormType" style='color:#000;' class="link" dataid='{HeightAbnormType_id}'><?php } echo empty($HeightAbnormType_Name)?$empty_str:'{HeightAbnormType_Name}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaHeightAbnormType" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Познавательная функция (возраст развития) (мес.): <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputGnostic" style='color:#000;' class="link" dataid='{AssessmentHealth_Gnostic}'><?php } echo empty($AssessmentHealth_Gnostic)?$empty_str:'{AssessmentHealth_Gnostic}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaGnostic" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Моторная функция (возраст развития) (мес.): <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputMotion" style='color:#000;' class="link" dataid='{AssessmentHealth_Motion}'><?php } echo empty($AssessmentHealth_Motion)?$empty_str:'{AssessmentHealth_Motion}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaMotion" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Эмоциональная и социальная (контакт с окружающим миром) функции (возраст развития) (мес.): <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputSocial" style='color:#000;' class="link" dataid='{AssessmentHealth_Social}'><?php } echo empty($AssessmentHealth_Social)?$empty_str:'{AssessmentHealth_Social}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaSocial" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Предречевое и речевое развитие (возраст развития) (мес.): <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputSpeech" style='color:#000;' class="link" dataid='{AssessmentHealth_Speech}'><?php } echo empty($AssessmentHealth_Speech)?$empty_str:'{AssessmentHealth_Speech}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaSpeech" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Психомоторная сфера: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputNormaDisturbanceType" style='color:#000;' class="link" dataid='{NormaDisturbanceType_id}'><?php } echo empty($NormaDisturbanceType_Name)?$empty_str:'{NormaDisturbanceType_Name}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaNormaDisturbanceType" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Интеллект: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputNormaDisturbanceTypeU" style='color:#000;' class="link" dataid='{NormaDisturbanceType_uid}'><?php } echo empty($NormaDisturbanceTypeU_Name)?$empty_str:'{NormaDisturbanceTypeU_Name}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaNormaDisturbanceTypeU" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Эмоционально-вегетативная сфера: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputNormaDisturbanceTypeE" style='color:#000;' class="link" dataid='{NormaDisturbanceType_eid}'><?php } echo empty($NormaDisturbanceTypeE_Name)?$empty_str:'{NormaDisturbanceTypeE_Name}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaNormaDisturbanceTypeE" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>P: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputP" style='color:#000;' class="link" dataid='{AssessmentHealth_P}'><?php } echo empty($AssessmentHealth_P)?$empty_str:'{AssessmentHealth_P}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaP" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Ax: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputAx" style='color:#000;' class="link" dataid='{AssessmentHealth_Ax}'><?php } echo empty($AssessmentHealth_Ax)?$empty_str:'{AssessmentHealth_Ax}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaAx" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Fa: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputFa" style='color:#000;' class="link" dataid='{AssessmentHealth_Fa}'><?php } echo empty($AssessmentHealth_Fa)?$empty_str:'{AssessmentHealth_Fa}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaFa" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Ma: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputMa" style='color:#000;' class="link" dataid='{AssessmentHealth_Ma}'><?php } echo empty($AssessmentHealth_Ma)?$empty_str:'{AssessmentHealth_Ma}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaMa" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Me: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputMe" style='color:#000;' class="link" dataid='{AssessmentHealth_Me}'><?php } echo empty($AssessmentHealth_Me)?$empty_str:'{AssessmentHealth_Me}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaMe" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Группа здоровья: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputHealthKind" style='color:#000;' class="link" dataid='{HealthKind_id}'><?php } echo empty($HealthKind_Name)?$empty_str:'{HealthKind_Name}'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaHealthKind" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Случай диспансеризации 1 этап закончен: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputIsFinish" style='color:#000;' class="link" dataid='{EvnPLDispTeenInspection_IsFinish}'><?php } echo ($EvnPLDispTeenInspection_IsFinish == 2)?'Да':'Нет'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaIsFinish" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
			<div style='clear:both;'><div style='float:left;padding:5px 0;'>Направлен на 2 этап диспансеризации: <?php if($is_allow_edit) { ?><span id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputIsTwoStage" style='color:#000;' class="link" dataid='{EvnPLDispTeenInspection_IsTwoStage}'><?php } echo ($EvnPLDispTeenInspection_IsTwoStage == 2)?'Да':'Нет'; if($is_allow_edit) { ?></span><?php } ?></div><div id="EvnPLDispTeenInspection_data_{EvnPLDispTeenInspection_id}_inputareaIsTwoStage" class="input-area" style="float:left; margin-left:5px; display: none"></div></div>
		</div>
	</div>
</div>