<?php
/**
 * @package      MorbusPregn
 * @author       Пермяков Александр
 * @version      06.2013
 */
$empty_str = '<span class="empty">Не указано</span>';
$is_allow_edit = ('edit' == $accessType);
?>
<div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}" class="specifics">
	<div class="caption">
		<h2><span id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_toggleDisplayDiag" class="collapsible">Диагноз</span></h2>
		<div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_toolbarDiag" class="toolbar" style="display: none">
			<a id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_saveDiag" class="button icon icon-save16" title="Сохранить"><span></span></a>
		</div>
	</div>
	<div id="MorbusPregnDiag_{MorbusPregn_pid}_{Morbus_id}" style="display: <?php echo (empty($MorbusPregn_NumTumor))?'none':'block'; ?>; padding:0px 5px 25px; border: 1px solid #000;">
		<div class="data-row-container"><div class="data-row">Дата появления первых признаков заболевания: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputfirstSignDT" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregn_firstSignDT) ? $empty_str : '{MorbusPregn_firstSignDT}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareafirstSignDT" class="input-area"></div></div>
		<div class="data-row-container">
			<div class="data-row">Первое обращение в ЛПУ по поводу данного заболевания. Дата: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputfirstVizitDT" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregn_firstVizitDT) ? $empty_str : '{MorbusPregn_firstVizitDT}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareafirstVizitDT" class="input-area"></div>
			<div class="data-row seq">ЛПУ: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputLpu" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{Lpu_foid}'><?php echo empty($Lpu_foid_Name) ? $empty_str : '{Lpu_foid_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaLpu" class="input-area"></div>
		</div>
		<div class="data-row-container"><div class="data-row">Дата установления диагноза: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputsetDiagDT" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregn_setDiagDT) ? $empty_str : '{MorbusPregn_setDiagDT}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareasetDiagDT" class="input-area"></div></div>
		<div class="data-row-container"><div class="data-row">Регистрационный номер: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputNumCard" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregnBase_NumCard) ? $empty_str : '{MorbusPregnBase_NumCard}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaNumCard" class="input-area"></div></div>
		<div class="data-row-container">
			<div class="data-row">Дата взятия на учет в ОД: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputMorbusBaseSetDT" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusBase_setDT) ? $empty_str : '{MorbusBase_setDT}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaMorbusBaseSetDT" class="input-area"></div>
			<div class="data-row seq">Взят на учет в ОД: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoRegType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoRegType_id}'><?php echo empty($OnkoRegType_id_Name) ? $empty_str : '{OnkoRegType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoRegType" class="input-area"></div>
		</div>
		<div class="data-row-container">
			<div class="data-row">Дата снятия с учета в ОД: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputMorbusBaseDisDT" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusBase_disDT) ? $empty_str : '{MorbusBase_disDT}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaMorbusBaseDisDT" class="input-area"></div>
			<div class="data-row seq">Причина снятия с учета: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoRegOutType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoRegOutType_id}'><?php echo empty($OnkoRegOutType_id_Name) ? $empty_str : '{OnkoRegOutType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoRegOutType" class="input-area"></div>
		</div>
		<div class="data-row-container"><div class="data-row">Порядковый номер данной опухоли у данного больного: <span class="value"><?php echo empty($MorbusPregn_NumTumor) ? $empty_str : '{MorbusPregn_NumTumor}'; ?></span></div></div>
		<div class="data-row-container"><div class="data-row">Первично-множественная опухоль: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputTumorPrimaryMultipleType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{TumorPrimaryMultipleType_id}'><?php echo empty($TumorPrimaryMultipleType_id_Name) ? $empty_str : '{TumorPrimaryMultipleType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaTumorPrimaryMultipleType" class="input-area"></div></div>
		<div class="data-row-container"><div class="data-row">Признак основной опухоли: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsMainTumor" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsMainTumor}'><?php echo empty($MorbusPregn_IsMainTumor_Name) ? $empty_str : '{MorbusPregn_IsMainTumor_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsMainTumor" class="input-area"></div></div>
		<div class="data-row-container"><div class="data-row">Топография (локализация) опухоли: <span class="value"><?php echo empty($Diag_id_Name) ? $empty_str : '{Diag_id_Name}'; ?></span></div></div>
		<div class="data-row-container"><div class="data-row">Сторона поражения: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoLesionSide" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoLesionSide_id}'><?php echo empty($OnkoLesionSide_id_Name) ? $empty_str : '{OnkoLesionSide_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoLesionSide" class="input-area"></div></div>

		<h2 style='clear:both;'><span id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_toggleDisplayMorfo" class="collapsible">Морфологический тип опухоли</span></h2>
		<div id="MorbusPregnMorfo_{MorbusPregn_pid}_{Morbus_id}" style="display: <?php echo (empty($OnkoDiag_mid) && empty($MorbusPregn_NumHisto))?'none':'block'; ?>; padding:0px 5px 25px; border: 1px solid #000;">
			<div class="data-row-container"><div class="data-row">Морфологический тип опухоли. (Гистология опухоли): <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoDiag" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoDiag_mid}'><?php echo empty($OnkoDiag_mid_Name) ? $empty_str : '{OnkoDiag_mid_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoDiag" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Номер гистологического исследования: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputNumHisto" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregn_NumHisto) ? $empty_str : '{MorbusPregn_NumHisto}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaNumHisto" class="input-area"></div></div>
		</div>

		<div class="data-row-container">
			<div class="data-row">Стадия опухолевого процесса по системе TNM. T: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoT" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoT_id}'><?php echo !isset($OnkoT_id_Name) ? $empty_str : '{OnkoT_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoT" class="input-area"></div>
			<div class="data-row seq">N: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoN" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoN_id}'><?php echo !isset($OnkoN_id_Name) ? $empty_str : '{OnkoN_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoN" class="input-area"></div>
			<div class="data-row seq">M: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoM" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoM_id}'><?php echo !isset($OnkoM_id_Name) ? $empty_str : '{OnkoM_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoM" class="input-area"></div>
		</div>
		<div class="data-row-container"><div class="data-row">Стадия опухолевого процесса: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputTumorStage" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{TumorStage_id}'><?php echo empty($TumorStage_id_Name) ? $empty_str : '{TumorStage_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaTumorStage" class="input-area"></div></div>

		<h2 style='clear:both;'><span id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_toggleDisplayMeta" class="collapsible">Локализация отдаленных метастазов</span></h2>
		<div id="MorbusPregnMeta_{MorbusPregn_pid}_{Morbus_id}" style="display: <?php echo (!empty($MorbusPregn_IsTumorDepoUnknown_Name) || !empty($MorbusPregn_IsTumorDepoLympha_Name) || !empty($MorbusPregn_IsTumorDepoBones_Name) || !empty($MorbusPregn_IsTumorDepoLiver_Name) || !empty($MorbusPregn_IsTumorDepoLungs_Name) || !empty($MorbusPregn_IsTumorDepoBrain_Name) || !empty($MorbusPregn_IsTumorDepoSkin_Name) || !empty($MorbusPregn_IsTumorDepoKidney_Name) || !empty($MorbusPregn_IsTumorDepoOvary_Name) || !empty($MorbusPregn_IsTumorDepoPerito_Name) || !empty($MorbusPregn_IsTumorDepoMarrow_Name) || !empty($MorbusPregn_IsTumorDepoOther_Name) || !empty($MorbusPregn_IsTumorDepoMulti_Name))?'block':'none'; ?>; padding:0px 5px 25px; border: 1px solid #000;">
			<div class="data-row-container"><div class="data-row">Неизвестна: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoUnknown" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoUnknown}'><?php echo empty($MorbusPregn_IsTumorDepoUnknown_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoUnknown_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoUnknown" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Отдаленные лимфатические узлы: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoLympha" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoLympha}'><?php echo empty($MorbusPregn_IsTumorDepoLympha_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoLympha_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoLympha" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Кости: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoBones" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoBones}'><?php echo empty($MorbusPregn_IsTumorDepoBones_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoBones_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoBones" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Печень: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoLiver" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoLiver}'><?php echo empty($MorbusPregn_IsTumorDepoLiver_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoLiver_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoLiver" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Легкие и/или плевра: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoLungs" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoLungs}'><?php echo empty($MorbusPregn_IsTumorDepoLungs_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoLungs_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoLungs" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Головной мозг: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoBrain" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoBrain}'><?php echo empty($MorbusPregn_IsTumorDepoBrain_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoBrain_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoBrain" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Кожа: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoSkin" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoSkin}'><?php echo empty($MorbusPregn_IsTumorDepoSkin_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoSkin_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoSkin" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Почки: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoKidney" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoKidney}'><?php echo empty($MorbusPregn_IsTumorDepoKidney_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoKidney_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoKidney" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Яичники: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoOvary" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoOvary}'><?php echo empty($MorbusPregn_IsTumorDepoOvary_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoOvary_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoOvary" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Брюшина: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoPerito" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoPerito}'><?php echo empty($MorbusPregn_IsTumorDepoPerito_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoPerito_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoPerito" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Костный мозг: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoMarrow" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoMarrow}'><?php echo empty($MorbusPregn_IsTumorDepoMarrow_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoMarrow_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoMarrow" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Другие органы: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoOther" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoOther}'><?php echo empty($MorbusPregn_IsTumorDepoOther_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoOther_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoOther" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Множественные: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputIsTumorDepoMulti" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{MorbusPregn_IsTumorDepoMulti}'><?php echo empty($MorbusPregn_IsTumorDepoMulti_Name) ? $empty_str : '{MorbusPregn_IsTumorDepoMulti_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaIsTumorDepoMulti" class="input-area"></div></div>
		</div>

        <div class="data-row-container"><div class="data-row">Метод подтверждения диагноза: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoDiagConfType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoDiagConfType_id}'><?php echo empty($OnkoDiagConfType_id_Name) ? $empty_str : '{OnkoDiagConfType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoDiagConfType" class="input-area"></div></div>
        <div class="data-row-container"><div class="data-row">Выявлен врачом: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoPostType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoPostType_id}'><?php echo empty($OnkoPostType_id_Name) ? $empty_str : '{OnkoPostType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoPostType" class="input-area"></div></div>
        <div class="data-row-container"><div class="data-row">Обстоятельства выявления опухоли: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputTumorCircumIdentType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{TumorCircumIdentType_id}'><?php echo empty($TumorCircumIdentType_id_Name) ? $empty_str : '{TumorCircumIdentType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaTumorCircumIdentType" class="input-area"></div></div>
		<div class="data-row-container"><div class="data-row">Причины поздней диагностики: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoLateDiagCause" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoLateDiagCause_id}'><?php echo empty($OnkoLateDiagCause_id_Name) ? $empty_str : '{OnkoLateDiagCause_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoLateDiagCause" class="input-area"></div></div>
        <div class="data-row-container">
            <div class="data-row">Дата смерти: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputMorbusPregnBaseDeadDT" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregnBase_deadDT) ? $empty_str : '{MorbusPregnBase_deadDT}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaMorbusPregnBaseDeadDT" class="input-area"></div>
            <div class="data-row seq">Причина смерти: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputDiagDead" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{Diag_did}'><?php echo empty($Diag_did_Name) ? $empty_str : '{Diag_did_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaDiagDead" class="input-area"></div>
        </div>
        <div class="data-row-container"><div class="data-row">Аутопсия: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputAutopsyPerformType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{AutopsyPerformType_id}'><?php echo empty($AutopsyPerformType_id_Name) ? $empty_str : '{AutopsyPerformType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaAutopsyPerformType" class="input-area"></div></div>
        <div class="data-row-container"><div class="data-row">Результат аутопсии применительно к данной опухоли: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputTumorAutopsyResultType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{TumorAutopsyResultType_id}'><?php echo empty($TumorAutopsyResultType_id_Name) ? $empty_str : '{TumorAutopsyResultType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaTumorAutopsyResultType" class="input-area"></div></div>
	</div>

    {MorbusPregnChemTer}<!--«Химиотерапевтическое лечение»-->
    {MorbusPregnRadTer}<!--«Лучевое лечение»-->
    {MorbusPregnGormTer}<!--«Гормоноиммунотерапевтическое лечение»-->
    {MorbusPregnHirTer}<!--«Хирургическое лечение»-->

    <!-- «Специальное лечение»-->
	<div style="display: <?php echo (true) ? 'block' : 'none'; ?>; clear: both;">
		<div class="caption">
			<h2><span id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_toggleDisplayTer" class="collapsible">Специальное лечение</span></h2>
			<div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_toolbarTer" class="toolbar" style="display: none">
				<a id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_saveTer" class="button icon icon-save16" title="Сохранить"><span></span></a>
			</div>
		</div>
		<div id="MorbusPregnTer_{MorbusPregn_pid}_{Morbus_id}" style="display: <?php echo (empty($MorbusPregn_specSetDT))?'none':'block'; ?>; padding:0px 5px 25px; border: 1px solid #000;">
			<div class="data-row-container"><div class="data-row">Дата начала специального лечения: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputspecSetDT" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregn_specSetDT) ? $empty_str : '{MorbusPregn_specSetDT}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaspecSetDT" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Дата окончания специального лечения: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputspecDisDT" class="value link"<?php } else { echo ' class="value"';} ?>><?php echo empty($MorbusPregn_specDisDT) ? $empty_str : '{MorbusPregn_specDisDT}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaspecDisDT" class="input-area"></div></div>
            <div class="data-row-container"><div class="data-row">Проведенное лечение первичной опухоли: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputTumorPrimaryTreatType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{TumorPrimaryTreatType_id}'><?php echo empty($TumorPrimaryTreatType_id_Name) ? $empty_str : '{TumorPrimaryTreatType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaTumorPrimaryTreatType" class="input-area"></div></div>
            <div class="data-row-container"><div class="data-row">Сочетание видов лечения: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoCombiTreatType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoCombiTreatType_id}'><?php echo empty($OnkoCombiTreatType_id_Name) ? $empty_str : '{OnkoCombiTreatType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoCombiTreatType" class="input-area"></div></div>
            <div class="data-row-container"><div class="data-row">Позднее осложнение лечения: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoLateComplTreatType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoLateComplTreatType_id}'><?php echo empty($OnkoLateComplTreatType_id_Name) ? $empty_str : '{OnkoLateComplTreatType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoLateComplTreatType" class="input-area"></div></div>
			<div class="data-row-container"><div class="data-row">Причины незавершенности радикального лечения: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputTumorRadicalTreatIncomplType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{TumorRadicalTreatIncomplType_id}'><?php echo empty($TumorRadicalTreatIncomplType_id_Name) ? $empty_str : '{TumorRadicalTreatIncomplType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaTumorRadicalTreatIncomplType" class="input-area"></div></div>
		</div>
	</div>

    <!-- «Контроль состояния»-->
    <div style="display: <?php echo (true) ? 'block' : 'none'; ?>; clear: both;">
        <div class="caption"><h2><span id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_toggleDisplayControl" class="collapsible">Контроль состояния</span></h2></div>
        <div id="MorbusPregnControl_{MorbusPregn_pid}_{Morbus_id}" style="display: block; padding:0px 5px 25px; border: 1px solid #000;">
            {MorbusPregnBasePersonState}<!--«Общее состояние пациента»-->
            <div class="data-row-container"><div class="data-row">Клиническая группа: <span<?php if ($is_allow_edit) { ?> id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputOnkoStatusYearEndType" class="value link"<?php } else { echo ' class="value"';} ?> dataid='{OnkoStatusYearEndType_id}'><?php echo empty($OnkoStatusYearEndType_id_Name) ? $empty_str : '{OnkoStatusYearEndType_id_Name}'; ?></span></div><div id="MorbusPregn_{MorbusPregn_pid}_{Morbus_id}_inputareaOnkoStatusYearEndType" class="input-area"></div></div>
        </div>
    </div>

    {MorbusPregnBasePS}<!-- «Госпитализация»-->

</div>



