<DataFile>
	<Учреждение>
		<ИНН_ЛПУ>{Lpu_Inn}</ИНН_ЛПУ>
		<КПП_ЛПУ>{Lpu_Kpp}</КПП_ЛПУ>
		<Дата_создания>{Document_Date}</Дата_создания>
		<Версия>{Document_Version}</Версия>
	</Учреждение>
	<Случаи>
			{sticks}
			<Случай>
				<Номер_СК>{SocCardNum}</Номер_СК>
				<Дата_рождения>{Person_BirthDay}</Дата_рождения>
				<Пол>{Person_Sex}</Пол>
				<Группа_инвалидности>{Person_DisabilityGroup}</Группа_инвалидности>
				<ОКАТО>{Person_OKATO}</ОКАТО>
				<Тип_местожит>{KLAreaType}</Тип_местожит>
				<Тип_льготы>{PrivilegeType_Code}</Тип_льготы>
				<Категория>{PrivilegeReason}</Категория>
				<Дата_начала>{Stick_begDate}</Дата_начала>
				<Дата_окончания>{Stick_endDate}</Дата_окончания>				
				<Причина>{StickReason}</Причина>
				<Диагноз>{Diag_Code}</Диагноз>
			</Случай>
			{/sticks}
	</Случаи>
</DataFile>